### ISSUE TITLE
Links to old MSDN documentation need updating

### ISSUE THREAD

**Issue by SQL-MisterMagoo** [MicrosoftDocs/visualstudio-docs#882] opened 2018-05-02 23:32 UTC
There are links on this page to MSDN which either take a very long time to load or fail to load at all. 
For example, the link to IVsTextBuffer is https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.textmanager.interop.ivstextbuffer(v=vs.140).aspx
For me, this link is timing out, which makes it impossible to use the documentation.
If there are corresponding pages on docs.microsoft.com, they should be updated here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 342173a2-f506-2560-5c56-dd2bd3871722
* Version Independent ID: b4f2602b-dee4-117d-88ab-e975faa01f64
* Content: [Editor Imports - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/editor-imports#feedback)
* Content Source: [docs/extensibility/editor-imports.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/extensibility/editor-imports.md)
* Service: **unspecified**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gregvanl** [comment] 2018-05-03 05:11
Hi @SQL-MisterMagoo I am not able to reproduce your issue. The link to IVsTextBuffer goes to a docs.microsoft.com API reference topic https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.textmanager.interop.ivstextbuffer?view=visualstudiosdk-2017 so redirection seems to be working. Can you try the page again? Perhaps there was an intermittent issue with redirection?

**Comment by SQL-MisterMagoo** [comment] 2018-05-03 06:26
Hi @gregvanl  - I've just noticed that is normal - the MSDN links redirect to docs, but when MSDN is slow and/or unresponsive you don't get that redirect. Is there a plan to just have these links go direct to docs?

Thanks

**Comment by leslierichardson95** [comment] 2020-12-11 23:06
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.

**Closed by leslierichardson95** 2020-12-11 23:06 UTC
Labels: Pri2, doc-bug, unspecified/svc, vs-ide-sdk/tech
