### ISSUE TITLE
F11 to enter or exit fullscreen

### ISSUE THREAD

**Issue by albertrw83** [MicrosoftDocs/visualstudio-docs#6245] opened 2020-12-25 23:31 UTC
[Enter feedback here]
I think it's actually F11 to exit fullscreen mode. not alt+shift+enter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68544507-42a5-6364-b7e2-17115bd5c88d
* Version Independent ID: e588245e-c033-32a1-18b8-8bb81d7461fe
* Content: [Full screen and virtual space mode - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-manage-editor-modes?view=vs-2019)
* Content Source: [docs/ide/how-to-manage-editor-modes.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-manage-editor-modes.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment] 2021-01-05 00:17
@albertrw83 Unfortunately, I cannot reproduce the behavior you describe by pressing F11. Only **Alt**+**Shift**+**Enter** works to enter or exit full screen mode. Visual Studio reserves the F11 function key for debugging or build actions (see the [Default keyboard shortcuts in Visual Studio](https://docs.microsoft.com/visualstudio/ide/default-keyboard-shortcuts-in-visual-studio?view=vs-2019) page for more details).

Perhaps you've reassigned the F11 keyboard shortcut previously? See the [Identify and customize keyboard shortcuts in Visual Studio](https://docs.microsoft.com/visualstudio/ide/identifying-and-customizing-keyboard-shortcuts-in-visual-studio?view=vs-2019#customize-a-keyboard-shortcut) page for more details about how to do (or undo) that.

We'll close this issue now as "non-repro", but we do appreciate you taking the time to give us feedback. We hope you'll reach out again if you have suggestions on how we can improve our documentation.

**Closed by TerryGLee** 2021-01-05 00:17 UTC
Labels: doc-bug, visual-studio-windows/prod, vs-ide-general/tech
