### ISSUE TITLE
visualstudio-docs

### ISSUE THREAD

**Issue by serverapidwalinz** [MicrosoftDocs/visualstudio-docs#6937] opened 2021-08-06 08:41 UTC
[ป้อนคำติชมที่นี่]

---
#### รายละเอียดเอกสาร

⚠ *อย่าแก้ไขส่วนนี้ กำหนดให้ต้องจัดทำ docs.microsoft.com ➟ การเชื่อมโยงปัญหา GitHub*

* ID: f307022f-0b34-372f-2185-b61227c110a7
* Version Independent ID: feabd94b-8396-4c5c-cbb4-cad94f2a476f
* Content: [Troubleshoot installation or upgrade issues - Visual Studio (Windows)](https://docs.microsoft.com/th-TH/visualstudio/install/troubleshooting-installation-issues?view=vs-2019)
* Content Source: [docs/install/troubleshooting-installation-issues.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/troubleshooting-installation-issues.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by serverapidwalinz** [comment] 2021-08-06 08:41
Something went wrong with the install.

You can troubleshoot the package failures by:

    1. Search for solutions using the search URL below for each package failure
    2. Modify your selections for the affected workloads or components and then retry the installation
    3. Remove the product from your machine and then install again

If the issue has already been reported on the Developer Community, you can find solutions or workarounds there. If the issue has not been reported, we encourage you to create a new issue so that other developers will be able to find solutions or workarounds. You can create a new issue from within the Visual Studio Installer in the upper-right hand corner using the "Provide feedback" button.

================================================================================

Package 'Microsoft.VisualCpp.CRT.ClickOnce.Msi,version=14.29.30040,language=en-US' failed to install.
    Search URL
        https://aka.ms/VSSetupErrorReports?q=PackageId=Microsoft.VisualCpp.CRT.ClickOnce.Msi;PackageAction=Install;ReturnCode=2203
    Details
        MSI: C:\ProgramData\Microsoft\VisualStudio\Packages\Microsoft.VisualCpp.CRT.ClickOnce.Msi,version=14.29.30040,language=en-US\vcpp_crt.redist.clickonce.msi, Properties:  REBOOT=ReallySuppress ARPSYSTEMCOMPONENT=1  MSIFASTINSTALL="7"  VSEXTUI="1" 
        Return code: 1603
        Return code details: Fatal error during installation.
        Message Id: 2203
        Message Details: The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2203. 
    Log
        C:\Users\Apidwalin\AppData\Local\Temp\dd_setup_20210806152939_001_Microsoft.VisualCpp.CRT.ClickOnce.Msi.log
    Impacted workloads
        .NET desktop build tools (Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools,version=16.10.31303.231)
    Impacted components
        ClickOnce Build Tools (Microsoft.Component.ClickOnce.MSBuild,version=16.0.28625.61)

--------------------------------------------------------------------------------

Package 'Microsoft.Net.4.8.SDK,version=4.8.3928.1' failed to install.
    Search URL
        https://aka.ms/VSSetupErrorReports?q=PackageId=Microsoft.Net.4.8.SDK;PackageAction=Install;ReturnCode=2203
    Details
        MSI: C:\ProgramData\Microsoft\VisualStudio\Packages\Microsoft.Net.4.8.SDK,version=4.8.3928.1\sdk_tools48.msi, Properties:  REBOOT=ReallySuppress ARPSYSTEMCOMPONENT=1  MSIFASTINSTALL="7"  VSEXTUI="1" 
        Return code: 1603
        Return code details: Fatal error during installation.
        Message Id: 2203
        Message Details: The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2203. 
    Log
        C:\Users\Apidwalin\AppData\Local\Temp\dd_setup_20210806152939_004_Microsoft.Net.4.8.SDK.log
    Impacted workloads
        .NET desktop build tools (Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools,version=16.10.31303.231)
    Impacted components
        .NET Framework 4.8 SDK (Microsoft.Net.Component.4.8.SDK,version=16.4.29313.120)

--------------------------------------------------------------------------------

Package 'Microsoft.AspNetCore.SharedFramework.5.0.5.0.8-servicing.21318.5.x86,version=16.10.31515.66' failed to install.
    Search URL
        https://aka.ms/VSSetupErrorReports?q=PackageId=Microsoft.AspNetCore.SharedFramework.5.0.5.0.8-servicing.21318.5.x86;PackageAction=Install;ReturnCode=2203
    Details
        MSI: C:\ProgramData\Microsoft\VisualStudio\Packages\Microsoft.AspNetCore.SharedFramework.5.0.5.0.8-servicing.21318.5.x86,version=16.10.31515.66\aspnetcore-runtime-5.0.8-servicing.21318.5-win-x86.msi, Properties:  REBOOT=ReallySuppress ARPSYSTEMCOMPONENT=1  DOTNETHOME="C:\Program Files (x86)\dotnet"  ALLOWMSIINSTALL="True" 
        Return code: 1603
        Return code details: Fatal error during installation.
        Message Id: 2203
        Message Details: The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2203. 
    Log
        C:\Users\Apidwalin\AppData\Local\Temp\dd_setup_20210806152939_005_Microsoft.AspNetCore.SharedFramework.5.0.5.0.8-servicing.21318.5.x86.log
    Impacted workloads
        .NET desktop build tools (Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools,version=16.10.31303.231)
    Impacted components
        .NET 5.0 Runtime (Microsoft.NetCore.Component.Runtime.5.0,version=16.10.31515.66)
        .NET SDK (Microsoft.NetCore.Component.SDK,version=16.10.31515.66)

--------------------------------------------------------------------------------

Package 'Microsoft.AspNetCore.SharedFramework.3.1.3.1.17-servicing.21318.8.x64,version=16.10.31515.66,chip=x64' failed to install.
    Search URL
        https://aka.ms/VSSetupErrorReports?q=PackageId=Microsoft.AspNetCore.SharedFramework.3.1.3.1.17-servicing.21318.8.x64;PackageAction=Install;ReturnCode=2203
    Details
        MSI: C:\ProgramData\Microsoft\VisualStudio\Packages\Microsoft.AspNetCore.SharedFramework.3.1.3.1.17-servicing.21318.8.x64,version=16.10.31515.66,chip=x64\aspnetcore-runtime-3.1.17-servicing.21318.8-win-x64.msi, Properties:  REBOOT=ReallySuppress ARPSYSTEMCOMPONENT=1  DOTNETHOME="C:\Program Files\dotnet"  ALLOWMSIINSTALL="True" 
        Return code: 1603
        Return code details: Fatal error during installation.
        Message Id: 2203
        Message Details: The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2203. 
    Log
        C:\Users\Apidwalin\AppData\Local\Temp\dd_setup_20210806152939_006_Microsoft.AspNetCore.SharedFramework.3.1.3.1.17-servicing.21318.8.x64.log
    Impacted workloads
        .NET desktop build tools (Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools,version=16.10.31303.231)
    Impacted components
        .NET Core 3.1 Runtime (LTS) (Microsoft.NetCore.Component.Runtime.3.1,version=16.10.31515.66)
        .NET SDK (Microsoft.NetCore.Component.SDK,version=16.10.31515.66)

**Comment by WilliamAntonRohm** [comment] 2021-08-06 17:07
Duplicate of #6938

**Closed by WilliamAntonRohm** 2021-08-06 17:07 UTC
Labels: duplicate, visual-studio-windows/prod, vs-installation/tech, cba, Pri1
