### ISSUE TITLE
Blank solution seems to have gone away

### ISSUE THREAD

**Issue by genifycom** [MicrosoftDocs/visualstudio-docs#8371] opened 2022-08-17 00:04 UTC
If you select "Create a new project" and follow the instructions to type solution into the search box, blank solution does not appear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7d9f53c-6ece-ea3c-9a51-9edd0efeebe3
* Version Independent ID: 9c927a8e-3ebd-0c8a-76cc-9b1c980b98a3
* Content: [Create projects & solutions - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/creating-solutions-and-projects?view=vs-2022)
* Content Source: [docs/ide/creating-solutions-and-projects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/creating-solutions-and-projects.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment] 2022-08-17 16:34
@genifycom Thanks for your feedback. This is a duplicate of a previously reported product problem (https://github.com/MicrosoftDocs/visualstudio-docs/issues/8261), wherein the optimal way to report it is via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE. (The engineering team uses the data from this tool to schedule bug fixes.)

Please be advised that this specific product problem has been recently reported; please visit https://developercommunity.visualstudio.com/t/Blank-Solution-project-template-missing/10114064?entry=problem to view the details and to upvote it, too.

**Closed by TerryGLee** 2022-08-17 16:34 UTC
Labels: product-feedback, duplicate, visual-studio-windows/prod, vs-ide-general/tech, Pri1
