### ISSUE TITLE
MS Testing Framework Does Not Support C++20 Features

### ISSUE THREAD

**Issue by JustaSimpleUser** [MicrosoftDocs/visualstudio-docs#9938] opened 2024-01-07 23:31 UTC
There's no mention of the limitation of MS Testing Framework that it cannot test units that are based extensively on C++20 standards.   This is a severe limitation considering that C++23 is due shortly.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 904d0bfe-b144-c2d1-3f1e-4db6c64e049e
* Version Independent ID: 6eda8810-d777-e4b7-0e1c-0bd7b16d450b
* Content: [Explore unit test tools and tasks - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/test/unit-test-your-code?view=vs-2022)
* Content Source: [docs/test/unit-test-your-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/test/unit-test-your-code.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment] 2024-01-30 18:01
@AbhitejJohn Do we have a contact who would know about this issue?

**Comment by Evangelink** [comment] 2024-01-30 19:22
The issue is not about `MSTest` but about `C++ Unit Test Framework`. @jakubch1 will be able to provide more info.

**Comment by Mikejo5000** [comment] 2024-01-30 20:22
Thanks!
________________________________

**Comment by jakubch1** [comment] 2024-01-31 07:24
I created `C++ Unit Test Framework` project and compiled it without issues with C++20 and C++23. 
@JustaSimpleUser  could you please provide feedback here: https://developercommunity.visualstudio.com/VisualStudio and also provide steps/solution to repro your issue?

**Comment by Mikejo5000** [comment] 2024-01-31 16:48
Closing it here, since there's a recommendation to move to Developer Community

**Closed by Mikejo5000** 2024-01-31 16:48 UTC
Labels: product-feedback, visual-studio-windows/prod, vs-ide-test/tech, Pri2

**Comment by JustaSimpleUser** [comment] 2024-02-02 02:33
To be honest, I don't fully recall what led me to this comment.  It may have stemmed from a specific compilation error or MSVS remark in my first testing framework tests.  Clearly, my report wasn't particularly good, and for that I apologize.

I'm happy to see this remain closed until, and if, my concerns are highlighted again the next time I try to implement a testing framework solution.
