### ISSUE TITLE
Hot restart not working

### ISSUE THREAD

**Issue by shaikh123456** [MicrosoftDocs/visualstudio-docs#6212] opened 2020-12-16 07:24 UTC
Hot restart is not working in vs 16.8.3 Severity	Code	Description	Project	File	Line	Suppression State Error		Error running hotrestart: 'An unexpected error occurred and the process has been terminated'. Command: 'sign -i="C:\Users\Shakil\AppData\Local\Temp\Xamarin\HotRestart\Bundles\16.8.000.260\e0eb8730\iRentalAppOffline.iOS.app" -p="C:\Users\Shakil\AppData\Local\Xamarin\iOS\Provisioning\Profiles\9fbde5f8-b1e6-445d-97e0-2552a972d82a.mobileprovision" -c="C:\Users\Shakil\AppData\Local\Xamarin\iOS\Provisioning\Certificates\7A63CC14C4A0EE77.p12" -pk="CFBundleIdentifier" -pv="com.integrasoft.iRentalAppOffline" -w="4045a893-85ab-429f-92eb-5d7972adfbd0"'	iRentalAppOffline.iOS

**Comment by WilliamAntonRohm** [comment] 2020-12-16 20:59
Duplicate of #6211

**Closed by WilliamAntonRohm** 2020-12-16 20:59 UTC
Labels: Pri3, cba, duplicate
