### ISSUE TITLE
How Big Is It?

### ISSUE THREAD

**Issue by johnyradio** [MicrosoftDocs/visualstudio-docs#2930] opened 2019-03-24 19:09 UTC
i cannot find info about the size of the offline installer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an offline installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017#feedback)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment] 2019-03-24 20:28
@johnyradio If you are referring to the bootstrapper file as described in "*Step 1 - Download the Visual Studio bootstrapper*", that file is approximately 1.45 MB. If you are referring to a layout as described in "*Step 2 - Create a local install cache*", then that size depends on the workloads and components that you want to install. However, there is a Note in that section that says that a "complete layout requires at least 35 GB of disk space."

**Comment by johnyradio** [comment] 2019-03-24 20:40
Thx, but wondering about the size of the offline installer, for a typical
config.

>

**Comment by TerryGLee** [comment] 2019-03-24 22:28
@johnyradio I'm not sure what you are asking; for an offline installation, the bootstrapper is what you need to create a locale cache, and the size of the local cache that you'll use to create your layout to install from depends on which workloads and components that you choose. There isn't a "typical config" because it depends on what you want to develop with Visual Studio; i.e. what programming language you want to use, what platform you want to develop for, what services you want to use to coordinate team development efforts, etc.

**Comment by johnyradio** [comment] 2019-03-25 00:10
the visual studio system requirement pages gives a range of hard disk space. But they also give an approximate size for "most" or "typical" users. 

so i mean the same thing microsoft means.

**Comment by TerryGLee** [comment] 2019-03-25 00:16
@johnyradio Thanks; it looks like then, that the [Visual Studio 2017 Product Family System Requirements](https://docs.microsoft.com/en-us/visualstudio/productinfo/vs2017-system-requirements-vs) has provided you with the information you seek; so, "Hard disk space: up to 130 GB of available space, depending on features installed; typical installations require 20-50 GB of free space."

I'll make sure to add a link to the system requirements page from the offline installation page. We'll get that added, soon.

**Comment by johnyradio** [comment] 2019-03-25 00:31
i believe that's the install footprint, correct?

i'm asking about the offline installer for a 20-50 GB install. thx

**Comment by TerryGLee** [comment] 2019-03-25 00:34
@johnyradio I believe it will be similar to what's previously been discussed, but I will inquire further and report back.

**Comment by johnyradio** [comment] 2019-03-25 01:00
i may have misunderstood. i didn't realize the "complete layout" meant the installer file. If so, that's the answer! thx

**Comment by tecky7** [comment] 2019-04-03 04:24
Microsoft has just finialised version (2019) of Visual Studio.

The size of the download version is 25GB per version,  This is based upon creating a local offline version.  But the installer can take up to a minimal of 92GB.  

![size](https://user-images.githubusercontent.com/44470935/55452354-483c1880-55cf-11e9-9d22-1d8658f1600b.jpg)
![install](https://user-images.githubusercontent.com/44470935/55452389-6dc92200-55cf-11e9-95b1-959f71bf3c27.jpg)

**Comment by tecky7** [comment] 2019-04-03 04:51
This means it takes a maximum of 2 hours to install the product.  As Visual Studio 2017 takes 4 hours to install.  Visual Studio 2017 requires "double network connectivity" in creating offline version.

You need WinRar to backup MS VS and the local cache.   As other utils, crash at certain point saying there is an error "at a directory".  Like AnytoIso.

![vs](https://user-images.githubusercontent.com/44470935/55453357-63a92280-55d3-11e9-8040-e4b783137108.jpg)

**Comment by Kuldeep-kd** [comment] 2019-04-16 12:51
If you are trying to download all the files in Visual Studio 2019, then the size is nearly 19.3 GB.

**Comment by tecky7** [comment] 2019-04-16 13:37
As programmer at BSc level @ Bolton University 

 I did a full off line download.  Without the use of the Internet later on.  And the size is still 25GB before installing all features in 2019.  That represents 93GB.  This includes latest updates version releases from Microsoft

**Comment by mwpowellhtx** [comment] 2019-04-30 20:50
How do we obtain the full offline image? That is, without necessarily having to itemize the litany of ``--add`` this, that, or the other dependencies? Is there a ``--full`` option, for instance? The delta, for instance, from the latest VS2017 offline layout is something like ``-23 GB``. That's quite a difference to make up.

**Comment by TerryGLee** [comment] 2019-04-30 20:58
@mwpowellhtx On the page, there's this that should help:

To create a complete local layout with all features (this will take a long time&mdash;we have _lots_ of features!), run:

   ```cmd
    vs_community.exe --layout c:\vslayout --lang en-US

**Comment by mwpowellhtx** [comment] 2019-04-30 21:05
@TerryGLee Right, I run that, but it delivers less than half what 2017 used to, delivering *15.9.11* for instance. How about the ***FULL*** image?

**Comment by TerryGLee** [comment] 2019-04-30 21:31
@mwalschburger Gotcha. This might prove useful: [Using --all](https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2019#using---all) from the _Command-line parameter examples for Visual Studio installation_ page.

**Comment by mwpowellhtx** [comment] 2019-04-30 22:29
@TerryGLee So if we go ``--layout --all``, that's what we're aiming for?

**Comment by mwpowellhtx** [comment] 2019-04-30 23:40
@TerryGLee Delayed and/or non-response I take to mean that did not work. I did verify ``--all --layout ...``, did not retrieve *all* for offline layout. Same result as without ``--all``.

**Comment by Kuldeep-kd** [comment] 2019-05-01 04:51
@mwpowellhtx Yeah, using --all or not, they have same effect and FYI Visual Studio 2019 has less setup image size than Visual Studio 2017... i.e Approx. 20GB. As I've confirmed from Microsoft care.

**Comment by mwpowellhtx** [comment] 2019-05-01 05:06
@Kuldeep-kd @TerryGLee My question is then, does this mean packages are deferred for later, during install, etc? That's what I'm trying to avoid if I can help it. That is, the more that is cached, *offline layout*, the better it will be for our install here.

**Comment by TerryGLee** [comment] 2019-05-01 19:03
Running a command with the --layout parameter (`vs_enterprise.exe --layout C:\layout`) creates a layout containing **all** packages for that version of Visual Studio for that edition. Then, installing from that layout by using the vs_enterprise.exe that is in the layout folder  with --all parameter (`C:\layout\vs_enterprise.exe --all`) installs all workloads and components from the layout.

No downloads should occur from the web unless a package in the layout is corrupted. This can be verified with the --verify command (`vs_enterprise.exe --layout C:\layout –verify`). For more information, see "How to verify a layout" section of the [Update a network-based installation of Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/update-a-network-installation-of-visual-studio?view=vs-2019#how-to-verify-a-layout) page.

Most issues can be fixed by using the --fix command (`vs_enterprise.exe --layout C:\layout --fix`). For more information, see the "How to fix a layout" section of the [Update a network-based installation of Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/update-a-network-installation-of-visual-studio?view=vs-2019#how-to-fix-a-layout) page.

Last but not least, if you still run in to problems, consider using the following resources:

- Our [**live chat**](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.
- Our [**Visual Studio conversation in the Gitter community**](https://gitter.im/Microsoft/VisualStudio)

Hope this helps,
~ Terry

**Comment by mwpowellhtx** [comment] 2019-05-01 19:06
@TerryGLee I understand the effect of those switches, yes; my question is really, from 2017 to 2019, what happened to the *~23 GB* or so of packaged bits? They were refactored out of band or what not? Are they installed after the fact?

**Comment by TerryGLee** [comment] 2019-05-01 20:09
@mwpowellhtx That's mostly attributed to a difference in the number of workloads, as I understand it. Visual Studio 2017 has 18 workloads, while Visual Studio 2019 has 17. Along with recategorizing workloads between the two versions, the main difference between the two is that Visual Studio 2017 includes a "Mobile development with Javascript" workload and Visual Studio 2019 does not.

**Comment by mwpowellhtx** [comment] 2019-05-01 20:13
> attributed to a difference in the number of workloads ...

I'm not sure what that means? That account for *23 GB* difference? That's a lot of difference, I think we can agree. That -1 delta from 17 to 19 is massive, then.

> Mobile development with JavaScript

What does this mean? What would the migration path be? Into *Eclipse*?

**Comment by DarranRowe** [comment] 2019-07-05 16:25
@mwpowellhtx
Is that delta really that massive? From the C++ side of things the v14.11, v14.12, v14.13, v14.14 and v14.15 C++ compiler toolsets were removed, and only the Visual Studio 15.9 version of the compiler, v14.16 is available to install in Visual Studio 2019. These compilers have an installed size of ~30.76GiB and an installer size of around 1GiB each.
There was also the removal of a lot of the Windows 10 SDKs, 4 of them, and the Windows 8.1 SDK. The installers are around 500Mib to 600MiB each, so that would be a minimum of around 2.5GiB.
This makes up at least 7.5GiB of the 23GiB easily.
There was the removal of some of the emulators and some of the older Android NDKs and Android SDKs. So I would say the majority of the difference is made up of the removal of the older stuff from the Visual Studio 2019 installer.

**Comment by mwpowellhtx** [comment] 2019-07-05 17:46
@DarranRowe I appreciate the insight explaining the differences. So it sounds like much of the delta was a decision to optimize the overall delivery, distill only the essentials. That makes a huge difference! :+1:

**Comment by ayenimiracle** [comment] 2019-07-24 06:36
My question is that, assuming I downloaded the setup files with the bootstrap with download all, then install option, where will the setup files saved to? I'm only asking this question because I want to copy those setup files to somewhere else and use it to reinstall it if eventually I  do a clean installation of windows?

**Comment by DarranRowe** [comment] 2019-07-24 13:32
There is an easier way, use the --layout command line option for the Visual Studio installer. You can get a description of how this works [here](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2019).

**Comment by ayenimiracle** [comment] 2019-07-24 14:51
#DarranRowe! You haven't answered my question. It's very simple to answer

**Comment by DarranRowe** [comment] 2019-07-24 15:00
My answer is very simple too. You wouldn't do what you are asking.
You would use the --layout option of the Visual Studio installer to create an offline installer and then just copy. I'm not even sure that if you copy the files from the cache that Visual Studio installer creates that it would use it at a later point.
However, if you really want to copy the files that the online installer creates then you will find it in %ProgramData%\Microsoft\VisualStudio\Packages.

**Comment by mwpowellhtx** [comment] 2019-07-24 17:11
@ayenimiracle The issue is not the installer temporary files, etc. That's not the issue. The concern are the bits that have essentially been re-engineered out of band. Meaning, reading past the hype, line towing, water pulling, etc, bits that previously were delivered in band in the monolithic install, run-times and so forth, are now deferred, and if I understand it correctly, you opt in to what you need. ``--layout`` is the right way to go there, I do this all the time tracking with the latest, stable updates.

**Comment by TerryGLee** [comment] 2019-07-25 20:03
Thanks everyone for your comments thus far; in them, questions have been asked and also answered, including that from the original poster. I am closing this issue now; however, you can still make comments to the thread if you wish. And if there is another question that anyone has that hasn't been answered here, please feel free to open a new GitHub Issue.

**Closed by TerryGLee** 2019-07-25 20:03 UTC
Labels: Pri1, area - installation, discussion, doc-bug, support-request, visual-studio-windows/prod, vs-installation/tech

**Comment by ayenimiracle** [comment] 2019-07-27 17:43
Can someone tells me how to modify the visual studio 2019 installer without removing the previous installed products?
