### ISSUE TITLE
No support for VS2019

### ISSUE THREAD

**Issue by sinand99** [MicrosoftDocs/visualstudio-docs#3122] opened 2019-04-20 18:36 UTC
Microsoft Code Analysis extension cannot be installed on Visual Studio 2019. Please update asap.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa028191-ecee-41ce-530c-263ada533515
* Version Independent ID: b43c95f9-90aa-8b15-7a5d-20f31b80d410
* Content: [Install Roslyn analyzers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/install-roslyn-analyzers?view=vs-2019#feedback)
* Content Source: [docs/code-quality/install-roslyn-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/install-roslyn-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by sujayvsarma** [comment] 2019-04-22 10:50
Also, the text on the VS UI and here are counter-intuitive. The link in the VS Properties page reads:

>"Run Code Analysis" as been deprecated **in favour of** FxCop Analyzers

This is not true. It is FxCop Analyzers that have been deprecated in favour or Roslyn Analyzers.

**Comment by gewarren** [comment] 2019-04-22 15:50
@sinand99 This looks like a dupe of #3126 ? 
Regarding the deprecation message, it's actually correct but I can see how it's confusing. FxCop analyzers are Roslyn analyzers; it's a NuGet package (or VSIX extension) containing analyzers that implement the most important static code analysis FxCop rules.

**Comment by gewarren** [comment] 2019-04-22 16:11
@sinand99 If you feel that the wording in the VS UI is confusing, please log an issue using Help > Send Feedback > Report a Problem in Visual Studio. We cannot fix product issues logged here in the documentation issues.

**Closed by gewarren** 2019-04-22 16:11 UTC
Labels: area - code analysis, doc feedback
