### ISSUE TITLE
This is bug in vs2019?

### ISSUE THREAD

**Issue by chancezheng** [MicrosoftDocs/visualstudio-docs#6839] opened 2021-07-07 08:02 UTC
![9BB84F11-BEDA-4702-BB57-A78AD3C89AEA](https://user-images.githubusercontent.com/31839078/124722486-b0130380-df3c-11eb-80dc-21a7c24e4064.png)

**Comment by WilliamAntonRohm** [comment] 2021-07-07 18:54
Duplicate of #6840

**Closed by WilliamAntonRohm** 2021-07-07 18:54 UTC
Labels: Pri3, cba, duplicate
