### ISSUE TITLE
Misleading wording in Note box  in "Using Microsoft Fakes in the CI" section

### ISSUE THREAD

**Issue by impact79** [MicrosoftDocs/visualstudio-docs#7866] opened 2022-04-05 14:30 UTC
Hello,
the following wording is misleading

![image](https://user-images.githubusercontent.com/22006750/161776900-f61f1322-4514-4e39-902b-9bd216747c3f.png)

Shouldn´t that be "source control" instead of "CI" ?

Regards,
Holger

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 069d29c9-b269-6e1f-08af-91ac135ebb1e
* Version Independent ID: cd993f76-8077-d566-4c48-0ab425c62b83
* Content: [Isolating Code Under Test with Microsoft Fakes - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/test/isolating-code-under-test-with-microsoft-fakes?view=vs-2019)
* Content Source: [docs/test/isolating-code-under-test-with-microsoft-fakes.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/test/isolating-code-under-test-with-microsoft-fakes.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment] 2022-04-05 23:27
Duplicate of #7867

**Closed by WilliamAntonRohm** 2022-04-05 23:27 UTC
Labels: duplicate, visual-studio-windows/prod, vs-ide-test/tech, Pri2
