### ISSUE TITLE
Quick Launch

### ISSUE THREAD

**Issue by Abedron** [MicrosoftDocs/visualstudio-docs#2595] opened 2019-02-16 17:52 UTC
I can`t find shortcuts for Quick Launch field. For this use is mouse required :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd6ebefd-fcc0-7e65-6450-c5908dbb61f8
* Version Independent ID: 83656699-f59b-5c22-94ad-bb2c8d58b2ae
* Content: [What's new in Visual Studio 2019](https://docs.microsoft.com/en-us/visualstudio/ide/whats-new-visual-studio-2019?view=vs-2017#better-search)
* Content Source: [docs/ide/whats-new-visual-studio-2019.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/whats-new-visual-studio-2019.md)
* Product: **visual-studio-dev16**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment] 2019-02-18 01:35
@Abedron Thanks for your feedback! To access the search feature in Visual Studio, press **Ctrl+Q**. 
We'll be sure that this gets documented.

**Comment by Abedron** [comment] 2019-02-21 20:10
Ctrl+Q not working (VS 2017 + Resharper, VS 2019 withour Resharper)

**Comment by TerryGLee** [comment] 2019-02-21 20:20
@Abedron Sorry to hear that **Ctrl**+**Q** isn't working for you. Unfortunately, I cannot reproduce at least part of what you've reported (VS 2019 without Resharper). At this point, this is no longer a problem with documentation, but instead a problem with the product. 

To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by Abedron** [comment] 2019-02-21 20:53
It is true :) thanks for link

**Comment by TerryGLee** [comment] 2019-02-21 22:30
@Abedron To close out on the documentation piece of the problem that you reported, I've merged a PR that updates the following pages with the shortcut key info for the Quick Launch search box:

* [Accessibility tips and tricks for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/accessibility-tips-and-tricks?view=vs-2017)
* [Welcome to the Visual Studio IDE](https://docs.microsoft.com/en-us/visualstudio/get-started/visual-studio-ide?view=vs-2017#popular-productivity-features)
* [Quickstart: First look at the Visual Studio IDE](https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-ide-orientation?view=vs-2017#quick-launch)
* [Productivity tips for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/productivity-tips-for-visual-studio?view=vs-2017#find-items-faster)

These updates should go live tomorrow afternoon. Meanwhile, I'll close this GitHub Issue.

Thanks,
~ Terry

**Closed by TerryGLee** 2019-02-21 22:30 UTC
Labels: area - IDE general, doc feedback, product feedback, visual-studio-dev16/prod
