### ISSUE TITLE
--includeOptional varying behaviours

### ISSUE THREAD

**Issue by andykn** [MicrosoftDocs/visualstudio-docs#2087] opened 2018-12-21 10:47 UTC
For install --includeOptional "not the recommended components" but for download ("layout") --includeOptional "includes the recommended...components". Is this correct, if so the difference in behaviours should be emphasised in this very clear and useful doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e97b834-fa82-6aa0-5913-4d5a8ed23366
* Version Independent ID: e988e3ea-8565-ca88-6ade-ab67425a51ae
* Content: [Use command-line parameters to install Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2017)
* Content Source: [docs/install/use-command-line-parameters-to-install-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/use-command-line-parameters-to-install-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment] 2018-12-21 22:48
@andykn Thanks for your feedback; we appreciate it! We'll investigate and report back. 
(@tydunkel - let's discuss this.)

**Comment by TerryGLee** [comment] 2019-01-25 23:23
@andykn I have checked in with the engineering team, who have assured me that this is stated correctly in the documentation. By design, the command-line parameters for the Install process and the Layout process work differently.

**Closed** 2019-01-25 23:47 UTC
Labels: area - installation, doc feedback, product question
