### ISSUE TITLE
Incorrect Example

### ISSUE THREAD

**Issue by chuckwolber** [MicrosoftDocs/visualstudio-docs#4000] opened 2019-09-26 16:19 UTC
In step 2 of the Integer Math example, the animated image is very obviously missing the "c = a + b" step. The code in the animation should not compile, let alone run.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f783f152-b26c-0ea4-8017-3929c7465368
* Version Independent ID: 8777c084-6578-8a7f-89db-80b3f9d547a7
* Content: [Tutorial: Create a simple C# console app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console?view=vs-2019#feedback)
* Content Source: [docs/get-started/csharp/tutorial-console.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-console.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment] 2019-09-26 20:27
Duplicate of https://github.com/MicrosoftDocs/visualstudio-docs/issues/3630

The animated GIF wasn't intended to duplicate the code preceding it; it was to show how auto-complete works.

However, we'll see what we can do to update the animated GIF.

**Comment by mairaw** [comment] 2019-12-06 17:35
It seems the duplicate issue got closed. Should this one be closed as well @TerryGLee?

**Comment by TerryGLee** [comment] 2019-12-10 20:50
@chuckwolber Thanks again for your input. We'll close this for now, but we'll consider replacing the animated GIF in a future update.

**Closed by TerryGLee** 2019-12-10 20:50 UTC
Labels: Pri3, doc-bug, visual-studio-windows/prod, vs-ide-general/tech
