### ISSUE TITLE
Debugging in visual studio code for mac

### ISSUE THREAD

**Issue by tiny-dancer** [MicrosoftDocs/visualstudio-docs#5623] opened 2020-07-24 02:20 UTC
When performing these steps on latest visual studio code for mac, there was no seperate docker-compose project created for debugging.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22e20f91-d94c-419c-3a64-7616af5e7429
* Version Independent ID: 0f4f0b1a-2506-ec3d-6bda-ccce7565cb64
* Content: [Get started with Docker - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/docker-quickstart?view=vsmac-2019)
* Content Source: [mac/docker-quickstart.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/docker-quickstart.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @heiligerdankgesang
* Microsoft Alias: **dominicn**

**Comment by WilliamAntonRohm** [comment] 2020-07-24 18:10
@tiny-dancer -- mg, thank you for your feedback.  Please consider these options:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@heiligerdankgesang -- Dominic, please look into this issue.

**Comment by heiligerdankgesang** [comment] 2020-12-03 18:01
This seems to work for me. 

@tiny-dancer - thanks for the patience. I see you mentioned "visual studio code for mac", but this documentation is for Visual Studio for Mac (different to Visual Studio Code). Seeing as this has been open for a while and I can't reproduce, I'll close this issue. If you're still seeing this in Visual Studio for Mac, please let me know and I'll follow up with you.

#please-close

**Closed by heiligerdankgesang** 2020-12-03 18:01 UTC
Labels: Pri2, doc-bug, visual-studio-mac/prod, vs-ide-general/tech
