### ISSUE TITLE
I noticed there should not be a space in the second line of un install

### ISSUE THREAD

**Issue by ggirton** [MicrosoftDocs/visualstudio-docs#7317] opened 2021-11-19 03:42 UTC
sudo ./ dotnet-uninstall-pkgs.sh

should be:

sudo ./dotnet-uninstall-pkgs.sh
[Enter feedback here]

Thank you!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd4c8a0-03f3-68df-2107-3934c2da5655
* Version Independent ID: 7cd4c8a0-03f3-68df-2107-3934c2da5655
* Content: [Visual Studio for Mac 17.0 and .NET on Apple Silicon machines - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/uninstall-net-2022?view=vsmac-2019)
* Content Source: [mac/uninstall-net-2022.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/uninstall-net-2022.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @heiligerdankgesang
* Microsoft Alias: **dominicn**

**Comment by WilliamAntonRohm** [comment] 2021-11-23 22:02
@ggirton -- thank you for catching this.  I have updated this article and it should be live by tomorrow.

Duplicate of https://github.com/MicrosoftDocs/visualstudio-docs/issues/7247

**Closed by WilliamAntonRohm** 2021-11-23 22:02 UTC
Labels: duplicate, doc-bug, vs-ide-general/tech, visual-studio-mac/prod, cba, Pri1
