### ISSUE TITLE
[Visual Studio Installer] Example for the response file does not work

### ISSUE THREAD

**Issue by matlo607** [MicrosoftDocs/visualstudio-docs#2920] opened 2019-03-22 15:13 UTC
The following example of response file does not work.
source: https://docs.microsoft.com/en-us/visualstudio/install/automated-installation-with-response-file?view=vs-2017
```powershell
.\vs_professional.exe --in C:\Users\mlongo\Documents\visual_studio_installer\example_doc.json
```
```json
{
  "installChannelUri": ".\\ChannelManifest.json",
  "channelUri": "https://aka.ms/vs/15/release/channel",
  "installCatalogUri": ".\\Catalog.json",
  "channelId": "VisualStudio.15.Release",
  "productId": "Microsoft.VisualStudio.Product.Enterprise",

  "installPath": "C:\\VS2017",
  "quiet": false,
  "passive": false,
  "includeRecommended": true,
  "norestart": false,

  "addProductLang": [
    "en-US",
    "fr-FR"
    ],

    "add": [
        "Microsoft.VisualStudio.Workload.ManagedDesktop",
        "Microsoft.VisualStudio.Workload.Data",
        "Microsoft.VisualStudio.Workload.NativeDesktop",
        "Microsoft.VisualStudio.Workload.NetWeb",
        "Microsoft.VisualStudio.Workload.Office",
        "Microsoft.VisualStudio.Workload.Universal",
        "Component.GitHub.VisualStudio"
    ]
}
```
![2019-03-22_16-05-52](https://user-images.githubusercontent.com/3038052/54832659-e02b2f80-4cbc-11e9-86fc-8d5eab083c91.png)
```
Exception of type 'Microsoft.VisualStudio.Setup.ChannelManifestDownloadException' was thrown.
```
log file:
```
2019-03-22T16:05:16 : Verbose : Visual Studio Installer (1.18.1096.130 : release) ["C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vs_installershell.exe","/finalizeInstall","install","--in","C:\\Users\\mlongo\\Documents\\visual_studio_installer\\example_doc.json","--locale","en-US","--activityId","4cd7b0cf-6ea6-439d-9b47-0ba73299ba75","--pipe","dcd6cecf-0528-4eff-9dc1-0fd729e81356"]
2019-03-22T16:05:17 : Verbose : Received the application ready notification
2019-03-22T16:05:17 : Verbose : ProgressBarService listening to ipc channel: progress-bar
2019-03-22T16:05:17 : Verbose : LoggerIpcRpcService listening to ipc channel: LoggerService
2019-03-22T16:05:17 : Verbose : LoggerIpcRpcService listening to ipc channel: LoggerService
2019-03-22T16:05:17 : Verbose : Telemetry Session ID: a5ada928-74fc-491f-b72c-ddbe85219761
2019-03-22T16:05:17 : Verbose : Starting ServiceHub Remote Settings client.
2019-03-22T16:05:17 : Verbose : Creating VS Telemetry Survey
2019-03-22T16:05:17 : Verbose : Creating commonError Service
2019-03-22T16:05:17 : Verbose : starting rpc process for common error
2019-03-22T16:05:17 : Verbose : RPC Factory: Get common error config provider
2019-03-22T16:05:17 : Verbose : FeaturesIpcRpcService listening to ipc channel: FeaturesProxy
2019-03-22T16:05:17 : Verbose : FeaturesIpcRpcService listening to ipc channel: FeaturesProxy
2019-03-22T16:05:17 : Verbose : Creating Start menu shortcut [shortcutName: Visual Studio Installer, targetPath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe]
2019-03-22T16:05:17 : Verbose : Starting the setup updater service.
2019-03-22T16:05:17 : Verbose : Service creation finished
2019-03-22T16:05:17 : Verbose : Installation finalized successfully.
2019-03-22T16:05:17 : Verbose : FeedbackIpcRpcService listening to ipc channel: FeedbackProxy
2019-03-22T16:05:18 : Verbose : Window ready
2019-03-22T16:05:18 : Verbose : Getting installed product summaries. [installerId: SetupEngine]
2019-03-22T16:05:18 : Verbose : Starting the installed products provider service.
2019-03-22T16:05:18 : Verbose : Starting the products provider service.
2019-03-22T16:05:18 : Verbose : Getting product summaries. [installerId: SetupEngine]
2019-03-22T16:05:18 : Verbose : Starting the installer service.
2019-03-22T16:05:19 : Verbose : Calling SetupEngine.Installer.Initialize. [locale: en-US]
2019-03-22T16:05:19 : Verbose : Connected to Hub Controller's client watch 'net.pipe://1b6d6d87c35704193d5ee7f3f04a1d00'
2019-03-22T16:05:19 : Verbose : Calling RemoteSettingsProviderService.Initialize(initializer) initializer: {"ClientName":"vs-xsetup","ClientVersion":"1.18.1096.130","RemoteSettingsFileName":"RemoteSettings_Installer.json","SerializedTelemetrySession":"{\"IsOptedIn\":true,\"Id\":\"a5ada928-74fc-491f-b72c-ddbe85219761\",\"HostName\":\"Dev14\",\"AppInsightsInstrumentationKey\":\"f144292e-e3b2-4011-ac90-20e5c03fbce5\",\"AsimovInstrumentationKey\":\"aif-312cbd79-9dbb-4c48-a7da-3cc2a931cb70\",\"ProcessStartTime\":636888639175700000}","ChannelOrProductId":"VS Installer","AppIdGuid":"42123B45-5471-4B16-81E7-5404CD93BCF1","ClientLocale":"en-US","Flights":[]}}
2019-03-22T16:05:19 : Verbose : ServiceHub Remote Settings client started.
2019-03-22T16:05:19 : Verbose : Getting the survey rules
2019-03-22T16:05:19 : Verbose : Calling RemoteSettingsProviderService.GetActionsAsync(actionPath), actionPath: vs\installer\surveyactions
2019-03-22T16:05:19 : Verbose : Calling RemoteSettingsProviderService.GetBooleanValue(collectionPath, key, defaultValue) collectionPath: Installer\Features\, key: ProblemsDlgButtons, defaultValue: false
2019-03-22T16:05:19 : Verbose : Calling RemoteSettingsProviderService.GetBooleanValue(collectionPath, key, defaultValue) collectionPath: Installer\Features\, key: CommonError, defaultValue: false
2019-03-22T16:05:19 : Verbose : Calling RemoteSettingsProviderService.GetBooleanValue(collectionPath, key, defaultValue) collectionPath: Installer\Features\, key: ProblemsDlgRetry, defaultValue: false
2019-03-22T16:05:19 : Verbose : Calling RemoteSettingsProviderService.GetBooleanValue(collectionPath, key, defaultValue) collectionPath: Installer\Features\, key: InstallationOptionsPageKS, defaultValue: false
2019-03-22T16:05:19 : Verbose : Calling RemoteSettingsProviderService.GetBooleanValue(collectionPath, key, defaultValue) collectionPath: Installer\Features\, key: CloudNativeDesc, defaultValue: false
2019-03-22T16:05:19 : Verbose : Calling RemoteSettingsProviderService.GetBooleanValue(collectionPath, key, defaultValue) collectionPath: Installer\Features\, key: CloudFirstDesc, defaultValue: false
2019-03-22T16:05:19 : Verbose : Calling RemoteSettingsProviderService.GetBooleanValue(collectionPath, key, defaultValue) collectionPath: Installer\Features\, key: RecWklds, defaultValue: false
2019-03-22T16:05:19 : Verbose : Calling RemoteSettingsProviderService.GetBooleanValue(collectionPath, key, defaultValue) collectionPath: Installer\Features\, key: SortWklds, defaultValue: false
2019-03-22T16:05:19 : Verbose : Calling RemoteSettingsProviderService.GetBooleanValue(collectionPath, key, defaultValue) collectionPath: Installer\Features\, key: ShowBitrate, defaultValue: false
2019-03-22T16:05:19 : Verbose : Calling RemoteSettingsProviderService.GetBooleanValue(collectionPath, key, defaultValue) collectionPath: Installer\Features\, key: RecommendSel, defaultValue: false
2019-03-22T16:05:19 : Verbose : Calling RemoteSettingsProviderService.GetBooleanValue(collectionPath, key, defaultValue) collectionPath: Installer\Features\, key: Surveys, defaultValue: false
2019-03-22T16:05:19 : Verbose : Calling RemoteSettingsProviderService.GetActionsAsync(actionPath), actionPath: vs\installer\commonerroractions
2019-03-22T16:05:19 : Verbose : ServiceHubExperimentationClient.setSharedProperty(name, value) called,
 [name: VS.ABExp.Flights] [value: lazytoolboxinit;fwlargebuffer;refactoring;spmoretempsbtn1;asloff;keybindgoldbarext;asynccsproj;vsfricheditor;completionapi;p4installer;preamy_treat1;tn-vsmacnps-7;seg_installer_ctrl]
2019-03-22T16:05:19 : Verbose : Started the setup updater service.
2019-03-22T16:05:19 : Verbose : SetupEngine.Installer.Initialize succeeded. [locale: en-US]
2019-03-22T16:05:19 : Verbose : Started the installer service.
2019-03-22T16:05:19 : Verbose : Calling SetupEngine.Installer.GetDriveInfo.
2019-03-22T16:05:19 : Verbose : Calling SetupEngine.Installer.IsElevated.
2019-03-22T16:05:19 : Verbose : SetupEngine.Installer.IsElevated succeeded.
2019-03-22T16:05:19 : Verbose : SetupEngine.Installer.GetDriveInfo succeeded.
2019-03-22T16:05:19 : Verbose : Resolved RemoteSettingsProviderService.GetBooleanValue(collectionPath, key, defaultValue) collectionPath: Installer\Features\, key: ProblemsDlgButtons, defaultValue: false, result: false
2019-03-22T16:05:19 : Verbose : Resolved RemoteSettingsProviderService.GetBooleanValue(collectionPath, key, defaultValue) collectionPath: Installer\Features\, key: InstallationOptionsPageKS, defaultValue: false, result: false
2019-03-22T16:05:19 : Verbose : Resolved RemoteSettingsProviderService.GetBooleanValue(collectionPath, key, defaultValue) collectionPath: Installer\Features\, key: RecommendSel, defaultValue: false, result: true
2019-03-22T16:05:19 : Verbose : Resolved RemoteSettingsProviderService.GetBooleanValue(collectionPath, key, defaultValue) collectionPath: Installer\Features\, key: Surveys, defaultValue: false, result: true
2019-03-22T16:05:19 : Verbose : Resolved RemoteSettingsProviderService.GetBooleanValue(collectionPath, key, defaultValue) collectionPath: Installer\Features\, key: CommonError, defaultValue: false, result: false
2019-03-22T16:05:19 : Verbose : ServiceHubExperimentationClient.postEvent(name, properties) called.
 [name: VS/ABExp/FlightRequest] [properties: {"VS.ABExp.Flight":"vswrecwklds","VS.ABExp.Result":"False"}]
2019-03-22T16:05:19 : Verbose : ServiceHubExperimentationClient.postEvent(name, properties) called.
 [name: VS/ABExp/FlightRequest] [properties: {"VS.ABExp.Flight":"vswshowbitrate","VS.ABExp.Result":"False"}]
2019-03-22T16:05:19 : Verbose : ServiceHubExperimentationClient.postEvent(name, properties) called.
 [name: VS/ABExp/FlightRequest] [properties: {"VS.ABExp.Flight":"vswcloudnativedesc","VS.ABExp.Result":"False"}]
2019-03-22T16:05:19 : Verbose : ServiceHubExperimentationClient.postEvent(name, properties) called.
 [name: VS/ABExp/FlightRequest] [properties: {"VS.ABExp.Flight":"vswproblemsdlgretry","VS.ABExp.Result":"False"}]
2019-03-22T16:05:19 : Verbose : ServiceHubExperimentationClient.postEvent(name, properties) called.
 [name: VS/ABExp/FlightRequest] [properties: {"VS.ABExp.Flight":"vswcloudfirstdesc","VS.ABExp.Result":"False"}]
2019-03-22T16:05:19 : Verbose : Resolved RemoteSettingsProviderService.GetBooleanValue(collectionPath, key, defaultValue) collectionPath: Installer\Features\, key: RecWklds, defaultValue: false, result: false
2019-03-22T16:05:19 : Verbose : Resolved RemoteSettingsProviderService.GetBooleanValue(collectionPath, key, defaultValue) collectionPath: Installer\Features\, key: CloudNativeDesc, defaultValue: false, result: false
2019-03-22T16:05:19 : Verbose : Resolved RemoteSettingsProviderService.GetBooleanValue(collectionPath, key, defaultValue) collectionPath: Installer\Features\, key: ShowBitrate, defaultValue: false, result: false
2019-03-22T16:05:19 : Verbose : Resolved RemoteSettingsProviderService.GetBooleanValue(collectionPath, key, defaultValue) collectionPath: Installer\Features\, key: ProblemsDlgRetry, defaultValue: false, result: false
2019-03-22T16:05:19 : Verbose : ServiceHubExperimentationClient.postEvent(name, properties) called.
 [name: VS/ABExp/FlightRequest] [properties: {"VS.ABExp.Flight":"vswsortwklds","VS.ABExp.Result":"False"}]
2019-03-22T16:05:19 : Verbose : Resolved RemoteSettingsProviderService.GetBooleanValue(collectionPath, key, defaultValue) collectionPath: Installer\Features\, key: CloudFirstDesc, defaultValue: false, result: false
2019-03-22T16:05:19 : Verbose : Resolved RemoteSettingsProviderService.GetBooleanValue(collectionPath, key, defaultValue) collectionPath: Installer\Features\, key: SortWklds, defaultValue: false, result: false
2019-03-22T16:05:20 : Verbose : ServiceHubExperimentationClient.postEvent(name, properties) called.
 [name: VS/ABExp/FlightRequest] [properties: {"VS.ABExp.Flight":"seg_installer_prod","VS.ABExp.Result":"False"}]
2019-03-22T16:05:20 : Verbose : ServiceHubExperimentationClient.postEvent(name, properties) called.
 [name: VS/ABExp/FlightRequest] [properties: {"VS.ABExp.Flight":"seg_installer_ctrl","VS.ABExp.Result":"True"}]
2019-03-22T16:05:20 : Verbose : Resolved RemoteSettingsProviderService.GetActionsAsync(actionPath) actionPath: vs\installer\commonerroractions, result: [{"Action":{"Rules":[{"ErrorCode":"0x80072ee7","PackagesAppliesTo":[],"CommonErrorMessage":"**Error 0x80072ee7&colon; No internet connection**\r\nThere is a problem connecting to our content delivery network servers. This might be a temporary server outage, or it could be an issue with your internet connection.\r\n\r\n**Fix**&colon; First, select View Logs and try to go to the URL in the report. If you can, try installing Visual Studio again. If you can not access the URL in the View Logs report, or if you are on an unreliable network, please try our recommended steps to [install Visual Studio 2017 on low&ndash;bandwidth or unreliable network environments](https://docs.microsoft.com/en-us/visualstudio/install/install-vs-inconsistent-quality-network).","Resources":[{"Locale":"en-us","Message":"**Error 0x80072ee7&colon; No internet connection**\r\nThere is a problem connecting to our content delivery network servers. This might be a temporary server outage, or it could be an issue with your internet connection.\r\n\r\n**Fix**&colon; First, select View Logs and try to go to the URL in the report. If you can, try installing Visual Studio again. If you can not access the URL in the View Logs report, or if you are on an unreliable network, please try our recommended steps to [install Visual Studio 2017 on low&ndash;bandwidth or unreliable network environments](https://docs.microsoft.com/en-us/visualstudio/install/install-vs-inconsistent-quality-network)."}]}]},"Precedence":0,"RuleId":"1343144E-3B75-4673-AA34-82674D5F4AB0"},{"Action":{"Rules":[{"ErrorCode":"-2146233033","PackagesAppliesTo":[],"CommonErrorMessage":"**Error &ndash;2146233033&colon; Package is corrupted**\r\nThe Visual Studio installer found a corrupted package. A package usually gets partially saved if the system was interrupted while downloading and writing the package to the disk.\r\n\r\n**Fix**&colon; This issue usually resolves by running a repair.","Resources":[{"Locale":"en-us","Message":"**Error &ndash;2146233033&colon; Package is corrupted**\r\nThe Visual Studio installer found a corrupted package. A package usually gets partially saved if the system was interrupted while downloading and writing the package to the disk.\r\n\r\n**Fix**&colon; This issue usually resolves by running a repair."}]}]},"Precedence":0,"RuleId":"17674D21-417D-45EB-B671-58D521DF3D57"},{"Action":{"Rules":[{"ErrorCode":"1303","PackagesAppliesTo":[],"CommonErrorMessage":"**Error 1303&colon; Access is denied**\r\nThere is a problem accessing a file or folder. This can happen if another process has locked a folder. \n \r\n\r\n**FIX**&colon; Rebooting and running a repair has helped unblock other users.","Resources":[{"Locale":"en-us","Message":"**Error 1303&colon; Access is denied**\r\nThere is a problem accessing a file or folder. This can happen if another process has locked a folder. \n \r\n\r\n**FIX**&colon; Rebooting and running a repair has helped unblock other users."}]}]},"Precedence":0,"RuleId":"384E5F4B-26EC-4277-94B4-74E2A843FBA9"},{"Action":{"Rules":[{"ErrorCode":"1714","PackagesAppliesTo":[],"CommonErrorMessage":"**Error Code 1714&colon; Cannot uninstall older version of an MSI**\r\nAn older version of an MSI is on your computer. You will need to uninstall it before you can install Visual Studio.\r\n\r\n**Fix**&colon; Please try the recommended steps to [troubleshoot MSI errors 1714 and 1612](https://aka.ms/VSMSIError)","Resources":[{"Locale":"en-us","Message":"**Error Code 1714&colon; Cannot uninstall older version of an MSI**\r\nAn older version of an MSI is on your computer. You will need to uninstall it before you can install Visual Studio.\r\n\r\n**Fix**&colon; Please try the recommended steps to [troubleshoot MSI errors 1714 and 1612](https://aka.ms/VSMSIError)"}]}]},"Precedence":0,"RuleId":"818EBFDE-E794-4A31-AA70-2C427B920C33"},{"Action":{"Rules":[{"ErrorCode":"0x80096004","PackagesAppliesTo":[],"CommonErrorMessage":"**Error 0x80096004&colon; Signature can't be verified**\r\nThere is a problem verifying the signature of a certificate. This usually happens when a package has been damaged.\r\n\r\n**FIX**&colon; First, select View Logs to get the name of the damaged package. In File Explorer, delete that package from the ProgramData\\Microsoft\\VisualStudio\\Packages folder and try installing Visual Studio again. If you are installing from a local or network layout, try following the recommended steps to [update a network&ndash;based installation of Visual Studio.](https://docs.microsoft.com/en-us/visualstudio/install/update-a-network-installation-of-visual-studio)","Resources":[{"Locale":"en-us","Message":"**Error 0x80096004&colon; Signature can't be verified**\r\nThere is a problem verifying the signature of a certificate. This usually happens when a package has been damaged.\r\n\r\n**FIX**&colon; First, select View Logs to get the name of the damaged package. In File Explorer, delete that package from the ProgramData\\Microsoft\\VisualStudio\\Packages folder and try installing Visual Studio again. If you are installing from a local or network layout, try following the recommended steps to [update a network&ndash;based installation of Visual Studio.](https://docs.microsoft.com/en-us/visualstudio/install/update-a-network-installation-of-visual-studio)"}]}]},"Precedence":0,"RuleId":"8A7E5F65-4C5B-43ED-8360-6542C6FC958C"},{"Action":{"Rules":[{"ErrorCode":"-2147024891","PackagesAppliesTo":["Win10SDK_Hidden_10.0.10240_2","Win10SDK_10.0.10586.212","Win10SDK_10.0.14393.795","Win10SDK_10.0.15063","Win10SDK_10.0.16299","Win10SDK_10.0.17134","Win10SDK_10.0.17763","Win10SDK_IpOverUsb","Win10_Emulator_10.0.14393.0","Win10_Emulator_10.0.15063","Win10_Emulator_10.0.15254"],"CommonErrorMessage":"**Error -2147024891&colon; Access is denied**\r\nThere is a problem accessing the registry or file system of this machine. This can happen if Windows Defender or other anti-virus software is restricting access. \n \r\n\r\n**FIX**&colon; Please review your anti-virus settings and ensure the Visual Studio Installer has unrestricted access to the registry and file system.","Resources":[{"Locale":"en-us","Message":"**Error -2147024891&colon; Access is denied**\r\nThere is a problem accessing the registry or file system of this machine. This can happen if Windows Defender or other anti-virus software is restricting access. \n \r\n\r\n**FIX**&colon; Please review your anti-virus settings and ensure the Visual Studio Installer has unrestricted access to the registry and file system."}]}]},"Precedence":0,"RuleId":"95BA07F6-0D32-4903-8507-8708A7B20898"},{"Action":{"Rules":[{"ErrorCode":"1618","PackagesAppliesTo":[],"CommonErrorMessage":"**Error 1618&colon; Another installation in progress**\r\nAnother program is using the Windows Installer Service. This might be due to an automatic update.\r\n\r\n**Fix**&colon; If Windows is installing updates, we recommend that you wait until the update is complete. If an installation did not close properly, select the Processes tab in Task Manager to locate and stop any MSIExec.exe entries. You can also restart your computer and try installing again.","Resources":[{"Locale":"en-us","Message":"**Error 1618&colon; Another installation in progress**\r\nAnother program is using the Windows Installer Service. This might be due to an automatic update.\r\n\r\n**Fix**&colon; If Windows is installing updates, we recommend that you wait until the update is complete. If an installation did not close properly, select the Processes tab in Task Manager to locate and stop any MSIExec.exe entries. You can also restart your computer and try installing again."}]}]},"Precedence":0,"RuleId":"B0F3C77A-61DC-4C6E-945B-60B6519BC988"},{"Action":{"Rules":[{"ErrorCode":"1601","PackagesAppliesTo":[],"CommonErrorMessage":"**Error 1601&colon; Windows Installer Service unavailable**\r\nThere is a problem with the Windows Installer Service, or it has been turned off.\r\n\r\n**Fix**&colon; This problem usually resolves when you retry the Visual Studio installation after one of the following workarounds.\r\n1. Restart your computer. \r\n2. Make sure Windows Installer Service is turned on. Run Services.msc and double-click on Windows Installer. If it has turned off, change Status to Manual, then select Apply and OK. If it is already running, select Stop and then Start. \r\n3. If you are still getting this problem, try the [recommended Windows Installer service troubleshooting steps](https://support.microsoft.com/en-us/help/17588/fix-problems-that-block-programs-from-being-installed-or-removed).","Resources":[{"Locale":"en-us","Message":"**Error 1601&colon; Windows Installer Service unavailable**\r\nThere is a problem with the Windows Installer Service, or it has been turned off.\r\n\r\n**Fix**&colon; This problem usually resolves when you retry the Visual Studio installation after one of the following workarounds.\r\n1. Restart your computer.\r\n2. Make sure Windows Installer Service is turned on. Run Services.msc and double-click on Windows Installer. If it is turned off, change Status to Manual, then select Apply and OK. If it is already running, select Stop and then Start.\r\n3. If you are still getting this problem, try the [recommended Windows Installer service troubleshooting steps](https://support.microsoft.com/en-us/help/17588/fix-problems-that-block-programs-from-being-installed-or-removed))"}]}]},"Precedence":0,"RuleId":"DFC5CD1E-D038-4A37-B5DD-82A4D220E0B9"}]
2019-03-22T16:05:20 : Verbose : Resolved RemoteSettingsProviderService.GetActionsAsync(actionPath) actionPath: vs\installer\surveyactions, result: [{"Action":{"Rules":[{"EventName":"vs/willow/install-product","SurveyUrl":"https://www.surveymonkey.com/r/D7H9VVT?p13={Reserved.SessionId}&sku={VS.Willow.productId}","ResourceId":"","Delay":0,"Properties":[{"Name":"Context.Default.VS.Willow.locale","Comparison":"Equals","Value":"en-us"},{"Name":"VS.Willow.operationName","Comparison":"Equals","Value":"install"}],"Resources":{"en-US":{"Title":"Thank you for installing Visual Studio","Message":"While Visual Studio is Installing, we'd like to ask you a few questions so we can improve the quality of our product. This survey will open in your default web browser.."}}}]},"Precedence":0,"RuleId":"B1A67CE3-4F2B-420F-85F6-EE1E078DCCA9"}]
2019-03-22T16:05:20 : Error : Failed to start the products provider service. error: Exception of type 'Microsoft.VisualStudio.Setup.ChannelManifestDownloadException' was thrown. at ChannelManifestDownloadException: Exception of type 'Microsoft.VisualStudio.Setup.ChannelManifestDownloadException' was thrown.
2019-03-22T16:05:20 : Error : Failed to start the installed products provider service. error: Exception of type 'Microsoft.VisualStudio.Setup.ChannelManifestDownloadException' was thrown. at ChannelManifestDownloadException: Exception of type 'Microsoft.VisualStudio.Setup.ChannelManifestDownloadException' was thrown.
2019-03-22T16:05:20 : Verbose : Window showing
2019-03-22T16:05:20 : Error : Failed to get product summaries. [installerId: SetupEngine, error: Exception of type 'Microsoft.VisualStudio.Setup.ChannelManifestDownloadException' was thrown. at Microsoft.VisualStudio.Setup.ChannelManifestDownloadException: Exception of type 'Microsoft.VisualStudio.Setup.ChannelManifestDownloadException' was thrown.
   at Microsoft.VisualStudio.Setup.ProductsProviderService.<Initialize>d__5.MoveNext()]
2019-03-22T16:05:20 : Error : Failed to get installed product summaries. [installerId: SetupEngine, error: Exception of type 'Microsoft.VisualStudio.Setup.ChannelManifestDownloadException' was thrown. at Microsoft.VisualStudio.Setup.ChannelManifestDownloadException: Exception of type 'Microsoft.VisualStudio.Setup.ChannelManifestDownloadException' was thrown.
   at Microsoft.VisualStudio.Setup.ProductsProviderService.<Initialize>d__5.MoveNext()]
2019-03-22T16:05:20 : Verbose : Pipe: \\.\pipe\dcd6cecf-0528-4eff-9dc1-0fd729e81356 connection is established
2019-03-22T16:05:20 : Verbose : Pipe is closed
```

**Comment by TerryGLee** [comment] 2019-03-22 19:27
@matlo607 Could it be because the examples in the document use Visual Studio Enterprise (thus the line in the JSON files that list "productId": "Microsoft.VisualStudio.Product.Enterprise") and you used "vs_professional.exe" to access the layout response file, which is for Visual Studio Professional and not Visual Studio Enterprise?

**Comment by matlo607** [comment] 2019-03-25 09:47
Hello @TerryGLee ,
I replaced `"productId": "Microsoft.VisualStudio.Product.Enterprise"` by `"productId": "Microsoft.VisualStudio.Product.Professional"` and it failed with the same error.

**Comment by matlo607** [comment] 2019-03-25 10:31
I tried to understand if the product ID has changed.
From what I understood from the REST API:
- [https://aka.ms/vs/15/release](https://aka.ms/vs/15/release) sends back a list of available products and I found in the response ([visualstudio.release.json](https://github.com/MicrosoftDocs/visualstudio-docs/files/3002623/visualstudio.release.json.txt)) `"id": "Microsoft.VisualStudio.Product.Professional"`.
- [https://aka.ms/vs/15/release/channel](https://aka.ms/vs/15/release/channel) sends back a manifest (
[visualstudio.15.release.catalog.json](https://github.com/MicrosoftDocs/visualstudio-docs/files/3002707/visualstudio.15.release.catalog.json.txt)
) with various items and among them the channel ID `VisualStudio.15.Release`.

Please could you provide me an already working response file if you have one so that we understand if it is a regression or not ?

**Comment by TerryGLee** [comment] 2019-03-25 17:14
@matlo607 Thanks for the additional information. 
@tydunkel Could you please take a look at this?

**Comment by tydunkel** [comment] 2019-03-25 20:25
@matlo607 Thank you for the feedback! Can you file an issue through the [feedback tool](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2017) in the installer so we can collect more detailed logs?

There are a few issues that could be happening. With the `channelUri` and `installChannelUri` parameters specified, the installer will download that information on startup. If one of those URLs fails to download, you'll see this exception. Verify the machine can access both URLs and the `installCatalogUri`.

**Comment by matlo607** [comment] 2019-03-26 10:07
I opened a ticket at https://developercommunity.visualstudio.com/content/problem/505751/installation-using-a-response-file-fails.html

**Comment by TerryGLee** [comment] 2019-03-26 18:18
@tydunkel Please let me know if there is any documentation impact from this GitHub Issue. However, for now, since the problem is being handled in the Developer Community, I will close this issue. (Although, even closed, you can still comment on it.)

**Closed by TerryGLee** 2019-03-26 18:18 UTC
Labels: area - installation, doc feedback, support request
