### ISSUE TITLE
Default value or behavior when applicable_accessibilities is omitted?

### ISSUE THREAD

**Issue by binki** [MicrosoftDocs/visualstudio-docs#354] opened 2017-11-17 21:03 UTC
Hi,

When reading the docs at https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference#naming-conventions , it is unclear what omitting `applicable_accessibilities` does. From the example provided, which is:

```
# Dotnet Naming Conventions
[*.{cs,vb}] 
dotnet_naming_rule.async_methods_end_in_async.symbols  = any_async_methods
dotnet_naming_rule.async_methods_end_in_async.style    = end_in_async
dotnet_naming_rule.async_methods_end_in_async.severity = suggestion

dotnet_naming_symbols.any_async_methods.applicable_kinds           = method
dotnet_naming_symbols.any_async_methods.applicable_accessibilities = *
dotnet_naming_symbols.any_async_methods.required_modifiers         = async

dotnet_naming_style.end_in_async.required_suffix = Async
dotnet_naming_style.end_in_async.capitalization  = pascal_case
```

it looks like it is a required value and omitting it would give some behavior other than `*`. Otherwise, the example would not show it being explicitly set to `*`, right?

However, intuitively, it seems like the default value for this parameter should be `*` and one should omit it instead of specifying it if this is the case.

Which way is it? I can’t tell from the docs, so I’m filing this issue…

**Comment by gewarren** [comment] 2017-11-27 18:29
@binki I'm still waiting on the official answer, but I believe that If you omit this property, your naming rule will apply to all accessibilities. I'm in the process of updating the documentation.

**Comment by kuhlenh** [comment] 2017-11-30 16:51
Hi @binki  -- if you want your rule to apply to all accessibilities you must specify so with `*`. Leaving off this rule does not pick a default accessibility (see [source](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/NamingStyles/EditorConfig/EditorConfigNamingStyleParser_SymbolSpec.cs#L145)). Hope that helps!

**Comment by binki** [comment] 2017-11-30 17:21
@kuhlenh In my testing and in reading [the part of the source that actually applies the rules](https://github.com/dotnet/roslyn/blob/878ffad23b8b06cb229c9ab31eada7634a473508/src/Workspaces/Core/Portable/NamingStyles/Serialization/SymbolSpecification.cs#L94), omitting the `applicable_accessibilities` results in the same behavior as specifying `*`. This is because, when the rule is tested for applicability to a particular symbol, it considers an empty list to be a a wildcard. Thus, in the source you point out, the `"*"` case and the `null` case could both just return an empty list—the `_all` field is unnecessary.

**Comment by gewarren** [comment] 2019-04-19 17:43
@kendrahavens Can you clarify what the expected behavior is when applicable_accessibilities is omitted from a naming rule?

**Comment by jmarolf** [comment] 2019-04-20 01:15
if you do not specify accessibility options its as if you used `*`

**Comment by kendrahavens** [comment] 2019-04-20 01:19
If you feel this is an important product change we welcome PRs against our repo! I'll close this issue since it's not a documentation issue.

**Closed by kendrahavens** 2019-04-20 01:19 UTC
Labels: area - IDE general, doc feedback
