### ISSUE TITLE
Installer won't start if the path for `--layout` has trailing backslash

### ISSUE THREAD

**Issue by garyng** [MicrosoftDocs/visualstudio-docs#3234] opened 2019-05-12 06:04 UTC
`vs_enterprise.exe --layout "D:\xxxx" --lang en-US` is working, but `vs_enterprise.exe --layout "D:\xxxx\" --lang en-US` is not - the installer UI won't start.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an offline installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2019)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment] 2019-06-20 19:40
@tydunkel Inquiry: It looks like when you add a trailing backslash to the destination file location, the --layout command balks. Is this a known issue?

**Comment by tydunkel** [comment] 2019-06-20 19:44
@TerryGLee I am unaware of this issue. I will file an internal issue to investigate. Thanks!

**Comment by TerryGLee** [comment] 2019-06-20 19:58
@garyng Thanks for reporting this to us. We'll investigate it, per the comment from engineering. I'll close this GitHub Issue now, as this venue is meant for documentation feedback only.

As an FYI: in the future, if you want to track a product-related issue, please consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) tool to report it. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Closed by TerryGLee** 2019-06-20 19:58 UTC
Labels: area - installation, support-request, visual-studio-windows/prod, vs-installation/tech

**Comment by tydunkel** [comment] 2019-06-26 17:01
To close the thread, we confirmed offline that a trailing '\' issue was fixed in the 15.1 release and has not regressed since. Please file feedback through the Developer Community if you are still having issues so we can investigate further. Thanks!
