### ISSUE TITLE
Missing setting.

### ISSUE THREAD

**Issue by Daedalus72** [MicrosoftDocs/visualstudio-docs#888] opened 2018-05-04 07:52 UTC
You need to mention that the relative layout must have a height of 100dp because with the default setting (550dp) the controls beneath the relative layout are not visible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14465304-3ced-6b36-5054-a85ac11e667e
* Version Independent ID: 9d2d9ca3-8d71-b81c-dbbb-bf4b269db034
* Content: [Build apps with native UI using Xamarin in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/build-apps-with-native-ui-using-xamarin-in-visual-studio#solution)
* Content Source: [docs/cross-platform/build-apps-with-native-ui-using-xamarin-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/build-apps-with-native-ui-using-xamarin-in-visual-studio.md)
* Service: **unspecified**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by gewarren** [comment] 2018-05-08 18:27
@Daedalus72 thanks for the feedback. @charlespetzold could you update the topic as necessary?

**Comment by charlespetzold** [comment] 2018-05-09 16:57
@Daedalus72 , can you clarify what you mean? I assume that you're referring to the **WeatherApp** sample here:

https://github.com/xamarin/mobile-samples/tree/master/Weather

and the **Main.axml** file in the Android project here:

https://github.com/xamarin/mobile-samples/blob/master/Weather/WeatherApp.Android/Resources/layout/Main.axml

The `RelativeLayout` at the top does not have a height setting of 100dp, and it does not need one. The `layout_height` property of the `RelativeLayout` is set to `wrap_content`, which means that its height is based on the aggregate height of its four children, which are the two `TextView` controls, the `EditText`, and the `Button` that appear near the top of the page. The remainder of the page consists of `TextView` controls below the `RelativeLayout`.

**Comment by victork00** [comment] 2018-08-02 10:16
The TextView items overlay. I followed the instructions step by step.
I think the problem is RelativeLayout.
I'll need to improve my design skills.

**Comment by victork00** [comment] 2018-08-03 09:05
Don't worry I know now.

**Comment by victork00** [comment] 2018-08-03 13:08
Another problem that I ran into is the lines after the </RelativeLayout>.
the xmlns:android line needs to be declared for the code to recognise it.
Since the RelativeLayout is closed it's not recognising anymore the android:"properties" from the TextView blocks.
What should I do?

**Comment by victork00** [comment] 2018-08-03 13:10
*after the "</RelativeLayout>"

**Comment by victork00** [comment] 2018-08-03 13:10
"RelativeLayout"

**Comment by conceptdev** [comment] 2018-09-20 17:02
The complete sample is available [on GitHub](https://github.com/xamarin/mobile-samples/tree/master/Weather) - please review the files there as they are complete and able to be compiled and run.
Thanks.

**Comment by conceptdev** [comment] 2018-10-22 16:47
#please-close

**Closed** 2018-10-22 17:17 UTC
Labels: area - xamarin, doc feedback
