### ISSUE TITLE
Incorrect documentation for binaryLogger

### ISSUE THREAD

**Issue by paulomorgado** [MicrosoftDocs/visualstudio-docs#732] opened 2018-03-23 13:05 UTC
As per the [documentation](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-command-line-reference.md) I can do this:

    /binaryLogger:LogFile=log.binlog

However, this will create the `LogFile=log.binlog` file.

**Comment by gewarren** [comment] 2018-03-23 18:33
@paulomorgado thanks for the feedback. @Mikejo5000 can you take this one?

**Comment by Mikejo5000** [comment] 2018-03-23 18:45
@gewarren Yes, assigning to self

**Comment by paulomorgado** [comment] 2018-03-23 23:05
It's also a problem in msbuild.exe

**Comment by Mikejo5000** [comment] 2018-03-30 22:23
@rainersigwald Rainer, is this a bug?

**Comment by rainersigwald** [comment] 2018-03-30 22:29
@paulomorgado I don't see that behavior. What version of MSBuild are you using, and can you specify the exact command line?

```
s:\msbuild2>dir *log
 Volume in drive S is Source
 Volume Serial Number is E68B-B87E

 Directory of s:\msbuild2

File Not Found

s:\msbuild2>msbuild /binaryLogger:LogFile=log.binlog /t:TargetThatDoesNotExist MSBuild.sln /noconlog
Microsoft (R) Build Engine version 15.7.127.34537 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Some command line switches were read from the auto-response file "MSBuild.rsp". To disable this file, use the "/noautoresponse" switch.
C:\Program Files (x86)\Microsoft Visual Studio\Preview\EntInt\MSBuild\15.0\bin\msbuild.exe /noconlog /binaryLogger:LogFile=log.binlog /clp:Summary /m /t:TargetThatDoesNotExist /verbosity:minimal MSBuild.sln

s:\msbuild2>dir *log
 Volume in drive S is Source
 Volume Serial Number is E68B-B87E

 Directory of s:\msbuild2

03/30/2018  05:28 PM           790,490 log.binlog
               1 File(s)        790,490 bytes
               0 Dir(s)  291,101,491,200 bytes free
```

**Comment by paulomorgado** [comment] 2018-03-31 19:53
Have you tried 15.6.82.30579 or 15.7.66.2115, @rainersigwald?

**Comment by rainersigwald** [comment] 2018-04-03 16:09
I do see this problem with 15.6.82. Looks like it was fixed with Microsoft/msbuild#3098.

I'd say to leave the docs as they are since it's the intended behavior and will be fixed with 15.7. @Mikejo5000?

```
C:\work>dir *log
 Volume in drive C is BOOTCAMP
 Volume Serial Number is FC56-66FC

 Directory of C:\work

File Not Found

C:\work>msbuild /binarylogger:LogFile=log.binlog test.proj /noconlog
Microsoft (R) Build Engine version 15.6.82.30579 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\msbuild.exe /noconlog /binarylogger:LogFile=log.binlog test.proj

C:\work>dir *log
 Volume in drive C is BOOTCAMP
 Volume Serial Number is FC56-66FC

 Directory of C:\work

04/03/2018  11:03 AM             3,419 LogFile=log.binlog
               1 File(s)          3,419 bytes
               0 Dir(s)   5,040,222,208 bytes free
```

**Comment by Mikejo5000** [comment] 2018-04-03 16:40
Yes, since the fix will bring the docs up to date we shouldn't change anything.

**Comment by paulomorgado** [comment] 2018-04-03 21:11
I've been seeing this consistently being wrong version over version that I thought it was a documentation error.

But I do like the way it's documented better.

**Closed** 2018-05-02 22:27 UTC
Labels: Area - msbuild, enhancement
