### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by sinand99** [MicrosoftDocs/visualstudio-docs#3126] opened 2019-04-21 20:53 UTC
FxCop analyzers extension cannot be installed on VS2019 because of a coreditor reference error. Please update the extension

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eee67c1d-5856-93e0-e2d3-e9551436aabc
* Version Independent ID: b756aa96-bbb1-40e8-34ca-97f9939bf7e9
* Content: [Install FxCop analyzers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/install-fxcop-analyzers?view=vs-2019)
* Content Source: [docs/code-quality/install-fxcop-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/install-fxcop-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment] 2019-04-22 15:38
@mavasani Should this be logged at Developer Community or roslyn-analyzers?

**Comment by mavasani** [comment] 2019-04-22 16:00
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/2034. We are working on publishing the updated VSIX this week.

Tagging @jinujoseph

**Comment by gewarren** [comment] 2019-04-22 16:08
Thanks Manish.

**Closed by gewarren** 2019-04-22 16:08 UTC
Labels: area - code analysis, product feedback

**Comment by sinand99** [comment] 2019-04-22 17:08
Thank you @mavasani 
Waiting for the vsix release.

**Comment by sinand99** [comment] 2019-05-06 15:52
@mavasani  14 days and nothing is published. Why does it take so long?
