### ISSUE TITLE
Project properties for my VB project in VS2022 do NOT appear as described in this document

### ISSUE THREAD

**Issue by dsorak** [MicrosoftDocs/visualstudio-docs#8061] opened 2022-05-24 14:12 UTC
I am attempting to set "Conditional compilation symbols" in the properties of my Visual Basic project and this page is incorrect, or at the very least incomplete in regards to Visual Basic.

My Visual Basic.NET project Properties page does NOT appear as described here. The major differences are:

The left nav of the properties dialog does not have nested values. They only appear as a flat list:
Application
Compile
Debug
References
Resources
Services
Settings
Signing
My Extensions
Security
Publish
Code Analysis

The values that appear on the right when one of the above is selected appear in an "old style" dialog that has a white/gray background and not the black and updated look as described in the article.

How can this article be so wrong? WHY are the project properties so inconsistent between C# and VB!?!?!? I am running the latest VS2022:

Microsoft Visual Studio Professional 2022
Version 17.2.1
VisualStudio.17.Release/17.2.1+32516.85
Microsoft .NET Framework
Version 4.8.03761
<...>
Visual Basic Tools 4.2.0-4.22252.24+47cdc16a21bbb8a4aadfb666b011e2059e1be5d2
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61c8c1e0-2829-06c9-84fb-7ebb2dc4b6cd
* Version Independent ID: 4c33d76c-9078-76a3-84d4-9b2e57763913
* Content: [What is the Project Designer? - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/reference/project-properties-reference?view=vs-2022)
* Content Source: [docs/ide/reference/project-properties-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/project-properties-reference.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment] 2022-05-24 20:32
Duplicate of #8060.

**Closed by WilliamAntonRohm** 2022-05-24 20:32 UTC
Labels: duplicate, visual-studio-windows/prod, vs-ide-general/tech, cba, Pri2
