### ISSUE TITLE
Please add Under Investigation and Under Consideration to Suggestion Status section

### ISSUE THREAD

**Issue by mrlife** [MicrosoftDocs/visualstudio-docs#6568] opened 2021-04-07 13:06 UTC
https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2019#suggestion-status

Here are some screenshots:

<img width="158" alt="Screen Shot 2021-04-07 at 9 04 28 AM" src="https://user-images.githubusercontent.com/213164/113870911-573aa000-9780-11eb-9aa0-42231414a564.png">

<img width="158" alt="Screen Shot 2021-04-07 at 9 04 38 AM" src="https://user-images.githubusercontent.com/213164/113870941-5efa4480-9780-11eb-8e3d-4c707e799539.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 785f2716-1297-f343-24fa-705a42c2ff64
* Version Independent ID: 732cf4ab-6056-31a6-abda-c63a37f90e45
* Content: [Suggest a feature - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2019)
* Content Source: [docs/ide/suggest-a-feature.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/suggest-a-feature.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by madskristensen** [comment] 2021-04-07 14:50
@mrlife Those two states only apply to problem reports. This is by design, though we have a work item to look at aligning all states across the ticket types.

**Comment by mrlife** [comment] 2021-04-07 14:54
@madskristensen Thanks for clarifying that. I was trying to understand the status of some of my submitted issues but can't find definitions for these 2 statuses. Would you be able to provide a brief description here?

**Comment by madskristensen** [comment] 2021-04-07 14:59
The translation from problem to suggestion states are not perfect, but can be thought of as:

`Under Consideration` = `Under Review`
'Under Investigation' = 'On Roadmap'

**Comment by mrlife** [comment] 2021-04-07 15:05
@madskristensen Thank you, this really helps.

**Comment by WilliamAntonRohm** [comment] 2021-04-07 18:22
@mrlife -- thank you for your suggestion and followup.

@madskristensen -- thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Closed by WilliamAntonRohm** 2021-04-07 18:22 UTC
Labels: Pri1, visual-studio-windows/prod, vs-ide-general/tech
