### ISSUE TITLE
16.0 Object Library ?

### ISSUE THREAD

**Issue by IrakliLomidze** [MicrosoftDocs/visualstudio-docs#1952] opened 2018-11-22 11:02 UTC
Is it Available  Version 16.0 of  Object Library ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88fddd73-1fac-2149-71db-5f20c8c94934
* Version Independent ID: 46e037ee-a5fd-7274-b072-8df92ce70eda
* Content: [Office primary interop assemblies - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/office-primary-interop-assemblies?view=vs-2017)
* Content Source: [docs/vsto/office-primary-interop-assemblies.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/office-primary-interop-assemblies.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment] 2018-11-25 20:50
@IrakliLomidze Thanks for your feedback; this page is in our backlog to update. @John-Hart, FYI.

**Comment by John-Hart** [comment] 2019-03-05 03:28
This is a duplicate of #1056

**Comment by John-Hart** [comment] 2019-03-05 03:28
#please-close

**Comment by TerryGLee** [comment] 2019-03-05 08:52
Closing per request; thanks @John-Hart

**Closed by TerryGLee** 2019-03-05 08:52 UTC
Labels: area - VSTO and sharepoint, duplicate, product question
