### ISSUE TITLE
Download Visual Studio is broken

### ISSUE THREAD

**Issue by MySixSenses** [MicrosoftDocs/visualstudio-docs#6262] opened 2021-01-03 17:34 UTC
The link https://docs.microsoft.com/en-us/docs/install/install-visual-studio.md is broken and leads to a 404
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a35176f2-ca94-7bb8-08a5-9e415d364ef3
* Version Independent ID: a9f184a6-78b9-315b-4a02-1c93bd4c3940
* Content: [Getting Started with Visual Studio Tools for Unity](https://docs.microsoft.com/en-us/visualstudio/gamedev/unity/get-started/getting-started-with-visual-studio-tools-for-unity)
* Content Source: [gamedev/unity/get-started/getting-started-with-visual-studio-tools-for-unity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/gamedev/unity/get-started/getting-started-with-visual-studio-tools-for-unity.md)
* Product: **visual-studio-dev16**
* Technology: **vs-unity-tools**
* GitHub Login: @therealjohn
* Microsoft Alias: **johmil**

**Comment by therealjohn** [comment] 2021-01-04 14:37
I think this is a dupe of #6255 and will be fixed as soon as a pending PR is merged. 

Thanks!

**Comment by WilliamAntonRohm** [comment] 2021-01-04 21:55
@MySixSenses -- thank you for raising this issue.  As @therealjohn mentioned, there is a previous issue (#6255) on this same topic, which is in process now.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Closed by WilliamAntonRohm** 2021-01-04 21:55 UTC
Labels: cba, duplicate, visual-studio-dev16/prod, vs-unity-tools/tech

**Comment by WilliamAntonRohm** [comment] 2021-01-05 00:31
@MySixSenses -- thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.

@therealjohn -- thank you for your assistance.
