### ISSUE TITLE
Data Sciences Workload not listed on page but shows up in Visual Studio Installer as an option.

### ISSUE THREAD

**Issue by RyanWeishalla** [MicrosoftDocs/visualstudio-docs#7365] opened 2021-11-29 18:54 UTC
[Enter feedback here]
On this page, I do not see the component list for the Data Science workload, but when I run the installer it shows as an option to install.  Is the installer incorrect or this reference page?  I do not use that workload, so just giving feedback in case either the installer is incorrect or the page is missing that information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29a1009-5ef4-707b-258e-fe8bbe7275b6
* Version Independent ID: 00fac5a7-fc6d-c9cb-2d26-d820c7055890
* Content: [Visual Studio Enterprise workload and component IDs](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2022)
* Content Source: [docs/install/workload-component-id-vs-enterprise.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/workload-component-id-vs-enterprise.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment] 2021-11-30 20:21
Duplicate of #7270

Thank you for your feedback! This issue is tracked by https://github.com/MicrosoftDocs/visualstudio-docs/issues/7270.

**Closed by anandmeg** 2021-11-30 20:21 UTC
Labels: doc-bug, visual-studio-windows/prod, vs-installation/tech
