### ISSUE TITLE
Cookiecutter

### ISSUE THREAD

**Issue by jawineh** [MicrosoftDocs/visualstudio-docs#2762] opened 2019-02-24 22:21 UTC
Microsoftpython-skleam-classifier...

The code failed due to error of 'Pandas...' not included in the model. The associated Quickstart lesson has to be reviewed. Or?

**Comment by kraigb** [comment] 2019-02-25 22:32
What Python environments do you have installed? As it notes at the top of the article, you need the Anaconda3 Python distribution, which includes the necessary libraries like Pandas. If you're running against a straight CPython install (e.g. from python.org), then you won't have those packages inherently. Let me know.

**Comment by kraigb** [comment] 2019-02-26 15:44
@jawineh Your issue #2775 confirmed that you hadn't installed Anaconda3, correct? In that case, I assume we can close this one?

**Comment by kraigb** [comment] 2019-02-26 22:14
Closing, because I think this is resolved. Feel free to reopen if necessary.

**Closed by kraigb** 2019-02-26 22:14 UTC
Labels: area - python and R, doc feedback
