### ISSUE TITLE
Options, Text Editor, Advanced settings lacks a help page

### ISSUE THREAD

**Issue by mstasak** [MicrosoftDocs/visualstudio-docs#7756] opened 2022-03-08 14:07 UTC
This page describes the **Tools | Options | Text Editor | General** settings as expected for General Settings, but there is no corresponding documentation for **Tools | Options | Text Editor | Advanced** (from VS2022 CE's menu).  Pressing F1 from the Advanced settings page opens the General help page in my browser, which does not cover the Advanced settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c03f0366-9eb0-a623-57dc-23c34ca5c73a
* Version Independent ID: 4682db7d-610f-2cf1-523b-34fdc10a016f
* Content: [Options, Text Editor, General - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-general?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(VS.ToolsOptionsPages.Text_Editor.Advanced)%26rd%3Dtrue&view=vs-2022)
* Content Source: [docs/ide/reference/options-text-editor-general.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/options-text-editor-general.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment] 2022-03-08 17:37
@mstasak Thanks for letting us know. We plan to have this page published soon; meanwhile, we'll close this issue now as it's a duplicate of an identical & previously reported issue, https://github.com/MicrosoftDocs/visualstudio-docs/issues/7494. 

We appreciate your interest in improving the documentation!

**Closed by TerryGLee** 2022-03-08 17:37 UTC
Labels: visual-studio-windows/prod, vs-ide-general/tech, Pri2

**Comment by TerryGLee** [comment] 2022-03-30 18:09
@mstasak To follow up, this previously missing page is now published; see [Options dialog box: Text Editor > Advanced](https://docs.microsoft.com/visualstudio/ide/reference/options-text-editor-advanced).
