### ISSUE TITLE
Topic specifies Preview image should be 200x200 pixels but published extensions all appear to use 128x128 pixel images.

### ISSUE THREAD

**Issue by mbranscomb** [MicrosoftDocs/visualstudio-docs#3771] opened 2019-08-13 18:48 UTC
The topic states the Preview image must be 200x200 pixels but it's not clear where that 200 pixel image will ever be displayed. Extensions published on Visual Studio Marketplace all appear to use images that are 128x128 pixels e.g. https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsls-vs.

- Download and unzip the extension
- The `extension.vsixmanifest` defines the preview image as `<PreviewImage>Resources\Market_Cascade_128x.png</PreviewImage>`
- The file at `Microsoft.VisualStudio.LiveShare\Resources\Market_Cascade_128x.png` is 128x128 pixels.

This text would appear to be incorrect: 

>`<PreviewImage>` - This optional element is a relative path to an image file (png, bmp, jpeg) contained in the package. The preview image should be 200x200 pixels, and displayed in the details UI. If no `PreviewImage` element is specified, the UI uses a default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55af1eb8-318c-fac9-410d-550b74425218
* Version Independent ID: 5b62e93a-9d46-6cde-9293-9c775ae61816
* Content: [VSIX Extension Schema 2.0 Reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/vsix-extension-schema-2-0-reference?view=vs-2019)
* Content Source: [docs/extensibility/vsix-extension-schema-2-0-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/vsix-extension-schema-2-0-reference.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by WilliamAntonRohm** [comment] 2019-08-15 17:15
This is a duplicate of https://github.com/MicrosoftDocs/visualstudio-docs/issues/3770, already answered.

**Closed by WilliamAntonRohm** 2019-08-15 17:15 UTC
Labels: Pri2, visual-studio-windows/prod, vs-ide-sdk/tech
