### ISSUE TITLE
Can not connect password-protected accdb file

### ISSUE THREAD

**Issue by tangruixun** [MicrosoftDocs/visualstudio-docs#5182] opened 2020-04-26 05:11 UTC
The method described in this document can not connect a password-protected .accdb database file. It just generates a general connection error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c5b210-2ecd-fc40-54c9-38a8ba9c7493
* Version Independent ID: a9236354-4965-a214-17f7-746c20de8ec4
* Content: [Connect to data in an Access database - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/connect-to-data-in-an-access-database-windows-forms?view=vs-2019)
* Content Source: [docs/data-tools/connect-to-data-in-an-access-database-windows-forms.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/connect-to-data-in-an-access-database-windows-forms.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by msebolt** [comment] 2020-05-27 22:32
@tangruixun Apologies for the delay, re-assigning this to the author.

**Comment by ghogen** [comment] 2020-06-04 17:15
@tangruixun I was not able to reproduce this error, with a password-protected Access database and Visual Studio 2019 16.7 Preview build. Are you still getting this error? Make sure the database is not opened for exclusive use in Microsoft Access at the time you are trying to connect.

Note that if this is a product issue, you should enter it on the [DevCommunity](https://developercommunity.visualstudio.com/spaces/8/index.html) site.

**Comment by tangruixun** [comment] 2020-06-05 05:53
@ghogen I am using the latest stable version. This is still an issue. When I am trying to add a password-protected *.accdb DB connection as described in step 6, no matter what entered in the username/password fields, it always prompts a "can not open" error after click "Test Connection" button. If I replace it with *.mdb file, the test will is ok.

![image](https://user-images.githubusercontent.com/1871234/83839425-9b0ee400-a72e-11ea-9cbc-0d61071efe04.png)


VS version:
Microsoft Visual Studio Community 2019
Version 16.5.5
VisualStudio.16.Release/16.5.5+30104.148
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA271
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.5.236.49856
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.5.236.49856
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.5.236.49856
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.5.236.49856
Azure Functions and Web Jobs Tools

C# Tools   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Dotfuscator Community Edition   5.42.0.9514-e0e25f754
PreEmptive Protection - Dotfuscator CE

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30207.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.25+gdacdb9b7a1
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62003.05170
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.20225.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.8.0.0 for F# 4.7   16.5.0-beta.20181.6+85af456066acd4e76d2bc7821b44a325e46f2fca
Microsoft Visual F# Tools 10.8.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

**Comment by ghogen** [comment] 2020-06-05 17:38
I think the critical piece is the Microsoft Access Database Engine. 
https://www.microsoft.com/en-us/download/details.aspx?id=54920
What do you see at the registry key
HKEY_CLASSES_ROOT\Microsoft.ACE.OLEDB.16.0
or another version?
Is this with Office 365, 32 or 64 bit version?
Probably, we can't solve this here. You could contact product support, or enter a bug report at the Dev Community site (link in previous comment).

**Comment by ghogen** [comment] 2020-06-12 20:47
I think we'll need to close this as a documentation issue, as you'll need to investigate or work with support to figure out what the root cause it. Thanks.

**Closed by ghogen** 2020-06-12 20:47 UTC
Labels: Pri3, support-request, visual-studio-windows/prod, vs-data-tools/tech
