### ISSUE TITLE
Configure visual studio extension projects as 64-bit applications

### ISSUE THREAD

**Issue by coast77777777777** [MicrosoftDocs/visualstudio-docs#4260] opened 2019-11-01 00:33 UTC
Hello,

I am trying to write code generating components that leverage the visual studio extension sdk and visual studio interop.  My systems have routinely error-ed out due to memory. How can I develop the interop mux for extension sdk without 64 bit IDE? the links below explain some details.

The problem:
The solution view can handle about ~50 thousand files. Then devenv crashes with memory error. Happens every time like clockwork.  Is there any work around to allow devenv access to all 128 instead of just a few gigabytes?

Thanks, coast

https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-ide-64-bit-support?view=vs-2019
https://docs.microsoft.com/en-us/visualstudio/extensibility/whats-new-visual-studio-2019-sdk?view=vs-2019
https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/using-visual-studio-interop-assemblies?view=vs-2019

**Comment by msebolt** [comment] 2019-11-01 17:36
@coast77777777777 Thank you for the feedback, we're sorry for the issue.

The product team would best be apt to recommend a solution to the root cause of this, however you will need to submit log files to the [Visual Studio community](https://developercommunity.visualstudio.com/spaces/8/index.html).

Please refer to [this example](https://developercommunity.visualstudio.com/content/problem/113696/vs-20173-crashes-since-installation-of-kb4038788.html) and comment  below if there are any issues.

Otherwise, for more generally recommended ways to increase memory and performance, see [Performance tips and tricks](https://docs.microsoft.com/visualstudio/ide/visual-studio-performance-tips-and-tricks?view=vs-2019).

**Comment by msebolt** [comment] 2019-11-07 16:49
Closing the issue now, please comment below any questions.

**Closed by msebolt** 2019-11-07 16:49 UTC
Labels: Pri3, support-request
