### ISSUE TITLE
Code concistensy

### ISSUE THREAD

**Issue by skulas** [MicrosoftDocs/visualstudio-docs#1059] opened 2018-05-30 12:33 UTC
Microsoft.Office.Core.DocumentProperties exists (as used in void TestProperties() )
But Office.DocumentProperties doesn't exist as used in ReadDocumentProperty(string propertyName)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7941790-134c-39a5-d0e4-0df82f723870
* Version Independent ID: 11357b83-d186-2df2-f73e-adf79191ea9c
* Content: [How to: Create and Modify Custom Document Properties - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-create-and-modify-custom-document-properties)
* Content Source: [docs/vsto/how-to-create-and-modify-custom-document-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/how-to-create-and-modify-custom-document-properties.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment] 2018-05-30 21:07
@skulas Thanks for letting us know. We've assigned this to our backlog for consideration and future updates.

**Closed** 2018-05-30 21:08 UTC
Labels: Area - VSTO and Sharepoint, enhancement

**Comment by JackRainy** [comment] 2020-01-14 14:46
The issue is still valid. 
The `Office.DocumentProperties` which is mentioned in line `properties = (Office.DocumentProperties)this.CustomDocumentProperties;` does not exist.
