### ISSUE TITLE
Page without a link in Visual Studio Docs

### ISSUE THREAD

**Issue by AlexanderMace** [MicrosoftDocs/visualstudio-docs#126] opened 2017-05-21 18:32 UTC
There is no link addressing [this page](https://docs.microsoft.com/en-us/visualstudio/welcome-to-visual-studio) in Visual Studio Documentation. I would suggest to change the link in [this page]( https://docs.microsoft.com/en-us/visualstudio/) from [What's new in Visual Studio 2017](https://docs.microsoft.com/en-us/visualstudio/ide/whats-new-in-visual-studio) to [Welcome to Visual Studio 2017](https://docs.microsoft.com/en-us/visualstudio/welcome-to-visual-studio).

See the answer by Carlos Quintero to [a question of mine](https://social.msdn.microsoft.com/Forums/vstudio/en-US/20ecbc02-d194-40a1-b924-b03040d995ca/visual-studio-docs-organization?forum=visualstudiogeneral) in Visual Studio General Questions.

**Comment by kempb** [comment] 2017-06-19 18:27
Thanks for the feedback. We're in the process of considering the proper navigation on the VS IDE hub page, and we'll keep your comments in mind.

**Comment by ghogen** [comment] 2017-09-21 19:40
I agree this is a problem, but so far we haven't found a good solution. You can't just change the link to the What's New, and our design only allows the three links.

**Comment by ghogen** [comment] 2017-09-21 19:41
Closing this as By Design.

**Closed by ghogen** 2017-09-21 19:41 UTC
