### ISSUE TITLE
Include and exclude not mutually exclusive

### ISSUE THREAD

**Issue by corradin** [MicrosoftDocs/visualstudio-docs#3060] opened 2019-04-12 09:37 UTC
Might be my settings, but when I only use the include in modulePaths, like so: .*myassembly.* it also includes other assemblies, such as moq.dll. If then I explicitly exclude .*moq.* it will exclude moq.dll.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43dc6fcf-df9f-9d2a-5c6e-8da0f6925afc
* Version Independent ID: d0bf2cae-9b59-d537-7acb-7af5f560d8c1
* Content: [Customizing Code Coverage Analysis - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/customizing-code-coverage-analysis?view=vs-2019#feedback)
* Content Source: [docs/test/customizing-code-coverage-analysis.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/customizing-code-coverage-analysis.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment] 2019-09-06 22:21
@corradin That's interesting, because the [documentation states](https://docs.microsoft.com/en-us/visualstudio/test/customizing-code-coverage-analysis?view=vs-2019#exclude-and-include) that only if Include is empty does it include all assemblies. If you specify an assembly, then the documentation implies that it only includes that one assembly. But that's not what you're seeing in practice. @mayankbansal018 Can you clarify and let me know whether the docs need to be updated?

**Comment by mayankbansal018** [comment] 2019-09-18 09:37
Include & Exclude are not mutually exclusive, _**Exclude**_ will always take preference, meaning if an assembly is mentioned in both Exclude / Include, it will be excluded.

**Comment by gewarren** [comment] 2019-09-18 18:45
@mayankbansal018 Putting Exclude aside for now and assuming it's empty or omitted, if you specify a single assembly in Include, should other assemblies also be included?

**Comment by mayankbansal018** [comment] 2019-09-19 07:20
@gewarren If you specify an assembly in _Include_, then only that particular assembly will be instrumented. 

Similarly if you specify an assembly in _Exclude_, then only that particular assembly will be excluded from instrumentation, rest all will be included.

**Comment by gewarren** [comment] 2019-09-19 19:42
@corradin It sounds like you either have something in your runsettings file that's causing the unexpected behavior, or there's a bug in the product. If you think it's the latter, please log an issue by using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool. When you do this, your report becomes part of the work items that are tracked on Visual Studio [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). There, you can engage directly with the engineering team while they address and fix the problem.

**Closed by gewarren** 2019-09-19 19:42 UTC
Labels: Pri2, area - test, doc-bug, visual-studio-windows/prod, vs-ide-test/tech
