### ISSUE TITLE
To publish to a file share or path

### ISSUE THREAD

**Issue by regal60740** [MicrosoftDocs/visualstudio-docs#2185] opened 2019-01-09 19:57 UTC
I can publish to my computer and I can install program from folder but I can't open Chrome browser and go to the file share and install program. I always get various error messages for all WalkThroughs for ClickOnce. I wish these Walkthroughs were more clear. They are confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30631bf6-bd74-a200-27b4-277ea35325e8
* Version Independent ID: 45a25442-c600-2b20-e815-792bbf67a47a
* Content: [How to: Publish a ClickOnce Application using the Publish Wizard - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/how-to-publish-a-clickonce-application-using-the-publish-wizard?view=vs-2017)
* Content Source: [docs/deployment/how-to-publish-a-clickonce-application-using-the-publish-wizard.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/how-to-publish-a-clickonce-application-using-the-publish-wizard.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment] 2019-01-18 22:46
@regal60740 Are you trying to open it from Chrome on the same machine or another computer? On the local machine, this URL should work:
file:///C:/Users/mikejo/Downloads/appname.exe
On Edge, you are prompted to run, so I suspect the issue is Chrome permissions or, if you are trying to open from a remote computer, the access permissions on the file share.

**Comment by Mikejo5000** [comment] 2019-01-18 22:51
And actually, on Chrome this works, too, opening locally. The file shows up in the lower left of my Chrome window. If you are trying to open from a remote computer, the issue will revolve around perms. It's more of a general web/browser issue than an issue relating to this doc, though, so I'm closing this.

**Closed by Mikejo5000** 2019-01-18 22:51 UTC
Labels: area - deployment, doc feedback
