### ISSUE TITLE
Use of NET 5.0 in some templates

### ISSUE THREAD

**Issue by AndrewDavid007** [MicrosoftDocs/visualstudio-docs#7040] opened 2021-09-12 03:21 UTC
When I get to Step 4 "Name the project QuickDate, then select Create."
I am using VB 2022 (Preview) and I want to build it on NET 5.0 but the dropdown only goes as high as 4.8
I have NET 5.0 installed because I can select other templates that support its use.
Will these templates be updated or replaced?
Your attention is appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e5b432e-98af-2784-12f3-5da298a7a6a3
* Version Independent ID: 0d0b207d-4ea3-3716-3894-b898b279e667
* Content: [Introduction to projects and solutions - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/get-started/tutorial-projects-solutions?view=vs-2019)
* Content Source: [docs/get-started/tutorial-projects-solutions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/tutorial-projects-solutions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment] 2021-09-13 22:29
Duplicate of #7041

**Closed by WilliamAntonRohm** 2021-09-13 22:29 UTC
Labels: duplicate, visual-studio-windows/prod, vs-ide-general/tech, cba, Pri1
