### ISSUE TITLE
Report a problem is not available

### ISSUE THREAD

**Issue by bobsort** [MicrosoftDocs/visualstudio-docs#2888] opened 2019-03-18 10:38 UTC
If "Visual Studio interface" cannot be opened, how do you "Report new problem"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2386e67e-a67b-de55-db57-e29a83dcb410
* Version Independent ID: 6247fba9-4255-9a59-c206-0e8547e12335
* Content: [How to report a problem with Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2017)
* Content Source: [docs/ide/how-to-report-a-problem-with-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-report-a-problem-with-visual-studio.md)
* Product: **visual-studio-windows**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by mariaghiondea** [comment] 2019-03-18 16:41
Thank you for presenting this scenario to us! This is something that we are aware of and trying to find a way to mitigate, while still keeping the actionability of reports that we get with the Feedback Tool. 
As a workaround, you can also report a problem from the Visual Studio Installer. 
Please also see https://developercommunity.visualstudio.com/idea/398744/problems-cannot-be-reported-when-the-ide-doesnt-wo.html

As a side note, please log suggestions and problems about the product through Developer Community or the Feedback Tool. This is a medium that is used for problems about docs, and it's harder to track and make the connection.

Maria Ghiondea
Visual Studio Feedback System

**Comment by gewarren** [comment] 2019-03-18 17:10
Closing as a dupe of #2887 .

**Closed by gewarren** 2019-03-18 17:10 UTC
