### ISSUE TITLE
Differentiation between "Lines of Executable Code" vs "Line of Source Code" is missing.

### ISSUE THREAD

**Issue by xs2bharat** [MicrosoftDocs/visualstudio-docs#4531] opened 2019-12-19 14:42 UTC
In the link https://docs.microsoft.com/en-us/visualstudio/code-quality/code-metrics-values?view=vs-2019, differentiation between "Lines of Executable Code" vs "Lines of Source Code" is missing.

**Comment by msebolt** [comment] 2019-12-20 06:35
@xs2bharat Thank you for the feedback.

Lines of executable code can vary depending on the compiler, linker, etc.

What exactly do you mean by differentiation?

**Comment by Taschenbuch** [comment] 2020-01-08 19:26
No need to close this, when the issue is not fixed yet.
It only says "Lines of Code" in the docu but it is called "Lines of Executable Code" and "Lines of Source Code" in visual studio.

![grafik](https://user-images.githubusercontent.com/43114787/72008873-083c4d00-3255-11ea-9594-d71f679a2a97.png)

![grafik](https://user-images.githubusercontent.com/43114787/72008887-14c0a580-3255-11ea-8a5b-3db5119db106.png)


His question was: 
What is the difference between those two things. I dont understand it either. Does "executable code" means IL code? or is it codes without line breaks, without empty lines and without comments? In contrast to that is "source code" just simply adding ALL lines in every code file?

**Comment by WilliamAntonRohm** [comment] 2020-01-08 20:42
@xs2bharat, @Taschenbuch -- thank you for your feedback.  I closed this issue because it had been unanswered for over two weeks.  I appreciate your followup.

@Mikejo5000 -- please look into this issue.

**Comment by Mikejo5000** [comment] 2020-01-09 21:59
I would hazard a guess that "Lines of Code" in the doc (IL code) equates to "Lines of Executable Code" in the UI, but would be good to confirm. @mavasani to comment, and to let us know whether ALL lines of every code file are counted in "Lines of Source Code".

**Comment by mavasani** [comment] 2020-01-09 22:02
I presume the description in https://github.com/MicrosoftDocs/visualstudio-docs/issues/3979 has the context?

**Comment by Mikejo5000** [comment] 2020-01-09 23:11
Looks like it does, thanks! I'll update the doc.

**Closed** 2020-01-10 16:47 UTC
Labels: Pri3, doc-bug
