### ISSUE TITLE
CA1801: False alarm in wpf specially for DependencyPropertyChangedEventHandler

### ISSUE THREAD

**Issue by pranshu-bst** [MicrosoftDocs/visualstudio-docs#4004] opened 2019-09-27 08:15 UTC
Is there a specific reason that it can't ignore these type of events for WPF.
As I understand the warning is because DependencyPropertyChangedEventArgs is not derived from EventArgs.

What's the solution to this.?

**Comment by gewarren** [comment] 2019-09-27 16:28
@pranshu-bst I found what I think is your exact issue on the Roslyn-analyzers repo here: https://github.com/dotnet/roslyn-analyzers/issues/2458. It was marked as a duplicate of [this issue](https://github.com/dotnet/roslyn-analyzers/issues/2593), which suggests you name the parameters as discards `_` and `_1`.

Since this is not a documentation issue, I'm going to close this issue now.

**Comment by gewarren** [comment] 2019-09-27 16:29
I'll keep this issue open to add this suggestion to the documentation.

**Comment by Mikejo5000** [comment] 2019-12-20 20:26
The end of the "Cause" section discusses the use of the discard symbol, "_", for parameters to eliminate the warning when the parameter is present only for signature requirements (looks like a case of a "...parameter whose value is implicitly accessed at run time by a framework but is not referenced in code"). For other issues here, this would be a change to the warning as described in dotnet/roslyn-analyzers#2593

**Closed by Mikejo5000** 2019-12-20 20:26 UTC
Labels: Pri3, doc-enhancement, visual-studio-windows/prod, vs-ide-code-analysis/tech
