### ISSUE TITLE
https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017

### ISSUE THREAD

**Issue by 5U8cVs** [MicrosoftDocs/visualstudio-docs#1562] opened 2018-09-22 21:31 UTC
https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017
Where is the absolute minimal two-step command line process to 1) download the layout directory and 2) install all of it.  I do not need to spend hours trying to reverse engineer this, my desire, from your description.  Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an offline installation of Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by 5U8cVs** [comment] 2018-09-22 21:38
More information.   What I want from Microsoft is this.  I want to download a maximal layout directory.  Everything on offer is to be in the layout directory.  Then, with the computer NOT CONNECTED to the Internet I want to launch the installation such that everything available in the layout directory is properly installed.  This is the plan you guys created for me.  I want to use your plan.  I don';t understand what you have written because what you have written is too complicated.  I want two command lines.  One creates the layout directory.  The other installs everything in the layout directory.  Thank you.

**Comment by vbjay** [comment] 2018-11-25 13:57
Are you not able to see it?  To create a complete local layout with all features (this will take a long time—we have lots of features!), run:

```vs_community.exe --layout c:\vs2017layout --lang en-US```
If you are installing a different sku, use that exe in the command.  

"If you want to install a language other than English, change en-US to a locale from the List of language locales. Then, use the list of the components and workloads available to further customize your installation cache.  " Basically, if you want to only install specific workloads and components alter the command as such.  

The layout folder will have an installer that you run from.

**Comment by Jonathan811** [comment] 2019-02-21 16:57
FYI i have pro and enterprise license so why can't I just get the image easy.

It shouldn't be this difficult I'm paying £1000's for muppetry.

**Comment by vbjay** [comment] 2019-02-21 18:27
You need to change your view. The vs product has MANY optional packages. Their update cadence has also sped up. Iso deployment is not as feasible. Downloading a multi GB file and your internet crapping out on you is a rip your hair out feeling. So they made a web downloader that you can run and keep up to date by scheduling a run of the downloader. You can make your own ISO if desired. Frankly, this optimizes storage and allows for downloading needed packages only. So quit complaining and use the tool to create an offline install. Then you can make an ISO from the folder. You can even script using powershell and scheduled tasks.

**Comment by 5U8cVs** [comment] 2019-02-22 01:48
My view is that Microsoft does what Microsoft does the way Microsoft does it.  There is nothing that will change that.  Code base grows exponentially because of all those programmers slaving away putting in New! Improved! Features! while defects remain unsolved.  Decades in the same industry have inured me to abuse from vendors.  As long as the money keeps rolling in from the cash cow there is little motivation to execute painful game plans.  The captive base of customers insulates managers from the consequences of their actions.  I create software that my end users understand intuitively.  The big players do not.  As long as some executive signs the check the deal is good.  End of story.

**Comment by Jonathan811** [comment] 2019-02-22 17:13
"... make your own ISO if desired...." 

Yes that's what I did.  And 2017 works better than 2015 did.

When the links work........on the "Create an Offline installation...." webpage..................

Never ending story more like.

**Comment by vbjay** [comment] 2019-02-22 17:21
https://visualstudio.microsoft.com/downloads/

![image](https://user-images.githubusercontent.com/3629489/53259023-0d73c600-369c-11e9-9283-c8b91fd677cb.png)


Same files.  They work.  It's not that hard.  The article just had links that got altered.  It's not hard to find the links on the root download page.  Yes.  It would be nice if the links in the article stayed current.  However, it isn't a life ender.

**Comment by vbjay** [comment] 2019-02-22 17:33
Look at the benefits they are providing:

- Instead of downloading full ISO each time, you run the web downloader and it GASP updates the layout folder.  
- You can optionally only download what you need.  So if you don't want game dev or C++ workloads, don't download them.
- You can script as a scheduled task and keep the layout folder current.  

Quit moaning and see the great things they are doing to help us out.  WAAAAAA  I have to run a cmd line.  It's so HARD!!!!!

**Comment by vbjay** [comment] 2019-02-22 17:38
Would you look at that :astonished: 
![image](https://user-images.githubusercontent.com/3629489/53260045-a0156480-369e-11e9-8474-ae7e25a65260.png)

I wonder.  hmmmm. Maybe I can use teh export with command line....

**Comment by Jonathan811** [comment] 2019-02-22 17:38
What I like about the internet is the mature interactions you can have and enlightened conversations.

Not here obviously.

FYI I was running on UNIX 26 years ago. DOS is a pale imitation of a OS>

Are you worried about your MS shares?

**Comment by vbjay** [comment] 2019-02-22 17:40
No.  Just sick and tired of whiny snot nosed fools that can't figure it out and GASP see the benefits of the new offline installer.  Would you like to download XGB each time or update the needed packages?

**Comment by Jonathan811** [comment] 2019-02-22 17:41
FYI those options are not available on VS Pro at all.

I don't care it's unmetered ISP...............I just want it to work........as I said previously...............

**Comment by vbjay** [comment] 2019-02-22 17:44
Of course they are.  You have to have it installed first.  Once you have one box set up the way you like it, you can export the config and load it in the other.  If you need an offline install, generate it with the command line and use that setup.  You could even run setup in the offline and import.

**Comment by Jonathan811** [comment] 2019-02-22 17:47
Really.....
![image](https://user-images.githubusercontent.com/44299631/53260658-edf39200-36c9-11e9-81c3-9a020127b9d1.png)

**Comment by Jonathan811** [comment] 2019-02-22 17:49
Perhaps it's as movable as their windows 10 interface.

What users like is constant change because they haven't got a day job at all............or so MS thinks.

**Comment by vbjay** [comment] 2019-02-22 17:50
That's because you are in the middle of an install.  notice RESUME!!!

**Comment by vbjay** [comment] 2019-02-22 17:52
NO VS installed box
![image](https://user-images.githubusercontent.com/3629489/53260827-8117d200-36a0-11e9-8dcc-1f7fa106cec0.png)
Close inner workload config dialog.  


![image](https://user-images.githubusercontent.com/3629489/53260874-a4db1800-36a0-11e9-8a72-8b879c501a34.png)

**Comment by vbjay** [comment] 2019-02-22 18:59
Real tired of your Micro$oft attitude.

**Comment by vbjay** [comment] 2019-02-23 12:34
[Create local cache](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017#step-2---create-a-local-install-cache)

[Install from cache](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017#step-3---install-visual-studio-from-the-local-cache)

Amazing.  @5U8cVs

**Comment by TerryGLee** [comment] 2019-02-25 21:55
@5U8cVs Thanks for your initial feedback; after review of the documentation, we believe that the "[Use the command line to create a local cache](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017#use-the-command-line-to-create-a-local-cache)" section of this article, which presents three steps instead of two, describes the process:

1. [Download the bootstrapper](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017#step-1---download-the-visual-studio-bootstrapper) 
2. [Create a local cache](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017#step-2---create-a-local-install-cache)
3. [Install from the local cache](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017#step-3---install-visual-studio-from-the-local-cache)

However, if you are still experiencing issues with your offline install, we do have a [**live chat**](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues. Also note that you can suggest a feature, report a product problem, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/).

@Jonathan811 The bootstrapper download links on this page that were were (temporarily) not working as intended, are now fixed. Apologies for any inconvenience that that caused.  

Thanks,
~ Terry

**Closed by TerryGLee** 2019-02-25 21:55 UTC
Labels: area - installation, discussion, doc feedback, product feedback
