### ISSUE TITLE
Explanation on this document is so vague!

### ISSUE THREAD

**Issue by bobsort** [MicrosoftDocs/visualstudio-docs#2874] opened 2019-03-15 10:00 UTC
There is not enough Explanation in this document.

My Error is Unable to start debugging on the web server. Unable to connect to the remote server.
My remote server is localhost, pool version on my IIS is 4.5 and pool version on my app is 4.5. 
UAC is disabled, which means I don't need to run as administrator.

I CAN connect, debug and run my application with Visual Studio 2010, but it fails with error above in Visual studio  2017 (15.9.7)

I do not have Internet connection on my development machine which means I cannot press Report an issue button! I haven't install Web Platform Installer (WebPI). 

A solution or fix shouldn't require installing 3rd party components to be able to fix it.

It is not clear if the minor version of pool and project should match too

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12b3da70-ab86-495d-abfe-384f369660fe
* Version Independent ID: 2456d73a-68bd-cc6b-bff0-e7666e53f404
* Content: [Error: Unable to Start Debugging on the Web Server - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/error-unable-to-start-debugging-on-the-web-server?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(vs.debug.error.http)%3Bk(TargetFrameworkMoniker-.NETFramework&view=vs-2017#feedback)
* Content Source: [docs/debugger/error-unable-to-start-debugging-on-the-web-server.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/error-unable-to-start-debugging-on-the-web-server.md)
* Product: **visual-studio-windows**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment] 2019-03-15 15:37
Can you Debug > Start without Debugging, and then use Debug > Attach to Process?

**Comment by Mikejo5000** [comment] 2019-03-15 16:55
Regarding third party components, you mean Web Platform Installer? That is really an IIS issue, not a debugger issue (Not sure how you can install certain items like ASP.NET without an Internet connection, that's external to debugging tools.) Before trying to debug, make sure you can run the app from IIS and it works correctly.
Also, since you are running a local IIS, you might check this topic:
https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-enable-debugging-for-aspnet-applications?view=vs-2017

**Comment by bobsort** [comment] 2019-03-16 00:41
I cannot see the IIS process in Visual studio list to attach debugger to it, even though I can see it in Task manager. as I mentioned I can easily debug the same project using "Visual Studio 10" on same PC with no trouble.

As for your second comment, I know Web Platform installer is an external component, I was just quoting from the document that asking me to install something using that instead of directly listing the component required to be installed, WITHOUT mentioning how that would fix this problem.

I'll try to follow the suggestions in document you've linked, but as far as I read, the only section related is how to configure to use IIS for debugging which I already knew that and did it, just the same way that would do in Visual Studio 2010.

BTW I'm not sure why would I need "debug with <browser name>" instead of just debug, because there is nothing to browse in a webservice. I'm not sure why Microsoft thinks they should open some browser for it too!

**Comment by Mikejo5000** [comment] 2019-03-16 00:55
In Attach to Process dialog, did you select "Show processes from all users" at the bottom of the dialog? That may work if you don't see it in the list.

**Comment by Mikejo5000** [comment] 2019-03-16 01:08
Also, did you see this in the requirements for the page I linked you to:
- Select Development time IIS support when installing Visual Studio. (If necessary, rerun the Visual Studio Installer, select Modify, and add this component.)
This looks like a newer requirement in VS 2017...

**Comment by Mikejo5000** [comment] 2019-03-16 01:13
Skip the last item, it's specific to ASP.NET Core.

**Comment by bobsort** [comment] 2019-03-18 05:38
Regarding attach to process, yes I tried it the process is not there to attach to it. but once I run project on Visual Studio 2010, w3wp.exe process starts and then I can attach to it from Visual Studio 2017 and start debugging.
BTW when attaching to process. there is a security warning as below 

"Attaching to this process can potentially harm your computer. If the information below looks suspicious or you are unsure, do not attach to this process"

I'm still wondering why that specific process is not running when I start debug with visual studio 2017.

![attach](https://user-images.githubusercontent.com/2040435/54509032-05e5cb00-4983-11e9-8d8b-b4d9de50f099.PNG)

**Comment by Mikejo5000** [comment] 2019-03-19 19:06
Hmm, it appears that older versions of VS were issuing a command to start IIS. VS probably stopped issuing the command once IIS Express was shipped with the product. IIS Express is the default IIS host that runs apps in more recent versions of VS. iisexpress.exe is the process name.

I would suggest in your scenario starting and stopping IIS from IIS Manager, and not count on VS 2017 to do this.

I believe the security warning is by design. I will go ahead and close this, since you found a workaround and the GitHub issues here are really for docs, and this appears to be a product issue (I'd say Report a Problem, but you said you had no Internet access currently).

**Closed by Mikejo5000** 2019-03-19 19:06 UTC
Labels: area - debugging, support request
