### ISSUE TITLE
"Smart Lock and RAII Annotations" section refers to non-existent annotations

### ISSUE THREAD

**Issue by kobykahane** [MicrosoftDocs/visualstudio-docs#3132] opened 2019-04-23 12:32 UTC
None of the annotations mentioned under the "Smart Lock and RAII Annotations" section in this page appear to actually exist in the concurrencysal.h header, or in any other header.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3befc1e4-e459-fb78-f12e-db45a16e9f98
* Version Independent ID: 32f54ed6-6189-4d05-66aa-b0e7dc66680d
* Content: [Annotating Locking Behavior - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/annotating-locking-behavior?view=vs-2019#feedback)
* Content Source: [docs/code-quality/annotating-locking-behavior.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/annotating-locking-behavior.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment] 2019-09-27 18:01
investigating

**Comment by kobykahane** [comment] 2019-11-03 09:38
Any word on this?

**Comment by hwisungi** [comment] 2019-11-05 18:08
We identified the cause of the discrepancy and notified the owner for resolution. Those annotations are new annotations added for concurrency checks and are included in the header that is released in Visual Studio. However, Windows SDK ships an older version of the header that is missing the new annotations. Please wait for a later release of Windows header. Meanwhile, please try to use the version that is included in the Visual Studio installation, if possible, as that will be the version that will be used once WIndows SDK removes their redundant copy of the header.

**Comment by corob-msft** [comment] 2020-03-06 03:39
Reviewing old open issues, this looks like it's a product issue, waiting on the next version of the Windows SDK.

**Closed by corob-msft** 2020-03-06 03:39 UTC
Labels: visual-studio-windows/prod, vs-ide-code-analysis/tech
