### ISSUE TITLE
Download links NOT working............

### ISSUE THREAD

**Issue by Jonathan811** [MicrosoftDocs/visualstudio-docs#2730] opened 2019-02-21 16:55 UTC
Hello

Links for vs_pro and vs_ent don't work. They take you to a landing page saying thanks for downloading which then flips into an Ad page for MS Surface. Link below. 

https://www.microsoft.com/en-gb/

What is going on............MSDN saying it's exe version is 15.0..........why is this so Hard..........???????????????

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an offline installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment] 2019-02-21 18:57
@Jonathan811 Thanks for letting us know! I have reproduced the experience that you describe. For some reason, these links are no longer working as intended. They have worked correctly in the past and so I will investigate why they aren't working now. More, soon.

**Comment by vbjay** [comment] 2019-02-22 18:24
Root download page links work just fine.  
![image](https://user-images.githubusercontent.com/3629489/53262641-2af95d80-36a5-11e9-9ef7-30ccf68948e3.png)

https://visualstudio.microsoft.com/downloads/

**Comment by TerryGLee** [comment] 2019-02-22 19:32
@vbjay Thanks for verifying that the root download page is working, and for offering it as an alternative. :) 
On the [Create an offline installation of Visual Studio 2017](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017) page, we have links to specific SKUs because we thought that those would work better, in context. An internal investigation is still ongoing as to why that experience is not working as intended.

**Comment by vbjay** [comment] 2019-02-22 19:50
No problem.

**Comment by ravi2100** [comment] 2019-02-23 02:31
I want to confirm whether Visual Studio bootstrapper  exe and root page exe(v-professional) are same?@vbay and @TerryGlee

**Comment by vbjay** [comment] 2019-02-23 04:19
Of course they are.

**Comment by MCrank** [comment] 2019-02-23 14:43
@Jonathan811 If you need the links now for offline use here there are:

Credit to @jberezanski. I got them from the chocolatey packages in his repo
[ChocolateyPackages](https://github.com/jberezanski/ChocolateyPackages)

----
[Community](https://download.visualstudio.microsoft.com/download/pr/41217ce6-f73c-48b9-b679-e5193984336b/500a2965365fa0283c3c31e4837487d9/vs_community.exe)

[Professional](https://download.visualstudio.microsoft.com/download/pr/366df54c-35a5-4d91-9614-fc0044349ed7/dc65bed6acbf3e2bd2d3c388c57b9987/vs_professional.exe)

[Enterprise](https://download.visualstudio.microsoft.com/download/pr/324e8588-c90a-4229-947f-d60efec43018/0baa0fb3754413e8048d3625ddf5d585/vs_enterprise.exe)

**Comment by vbjay** [comment] 2019-02-23 14:52
Or you could just go to https://visualstudio.microsoft.com/downloads/

**Comment by vbjay** [comment] 2019-02-23 14:56
![image](https://user-images.githubusercontent.com/3629489/53287993-3b671200-3751-11e9-8fb3-0f6106915c36.png)

**Comment by vbjay** [comment] 2019-02-23 15:01
The downloads from the download site work just fine.

![image](https://user-images.githubusercontent.com/3629489/53288043-f2fc2400-3751-11e9-8da3-f239e4386287.png)

**Comment by MCrank** [comment] 2019-02-23 16:16
Yes they do except in my case I am just trying to download the bootstrapper programmatically in which case it just downloads the HTML of the 'Download' page, at least from PowerShell. Is there another way? Probably. Am I possibly doing something wrong? More than likely.

The problem here is that the links in the article for the individual bootstrappers are broken.

**Comment by TerryGLee** [comment] 2019-02-25 20:58
The download link issue is now fixed; thanks again @Jonathan811 for reporting the problem.

**Closed by TerryGLee** 2019-02-25 20:58 UTC
Labels: area - installation, doc feedback
