### ISSUE TITLE
The link under Specifying Test Settings for Visual Studio Tests is broken

### ISSUE THREAD

**Issue by eduard-malakhov** [MicrosoftDocs/visualstudio-docs#691] opened 2018-03-14 10:33 UTC
This link points to **https://docs.microsoft.com/en-us/devops-test-docs/test/specifying-test-settings-for-visual-studio-tests** that does not exist. Maybe, it is meant to be https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21ac034a-a498-f3e3-28d0-175b6fead219
* Version Independent ID: 747194a8-ffcf-60b3-b525-6f8fe00066a2
* Content: [Configure unit tests in Visual Studio by using a *.runsettings* file - Visual Studio | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file)
* Content Source: [docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment] 2018-03-14 18:28
@eduard-malakhov thanks for the feedback. I will fix this.

**Comment by gewarren** [comment] 2018-03-16 17:50
This is fixed in https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/1553.

**Comment by gewarren** [comment] 2018-03-16 20:52
Duplicate of #420

**Closed** 2018-03-23 17:43 UTC
Labels: Area - test, enhancement
