### ISSUE TITLE
Just ignore the complexity of switch

### ISSUE THREAD

**Issue by ChrisTorng** [MicrosoftDocs/visualstudio-docs#4262] opened 2019-11-01 08:39 UTC
The document tells me that "a large `switch` statement is a candidate for exclusion", and no good suggestion for me to take. Are there any real suggestion? If no, why not just ignore this warning on `switch`? We have "IDE0010 Populate switch" protecting us from forgetting to add a new case. I don't think I need more warning on large `switch`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a288d0-68c8-dd18-d54f-921a03b33cf3
* Version Independent ID: 0cce318f-63f0-4a2b-0c75-a9e6e0eb12e5
* Content: [CA1502: Avoid excessive complexity - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1502?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca1502.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1502.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by msebolt** [comment] 2019-11-01 20:14
@ChrisTorng  Thank you for the question, assigning this to the author for review.

For non-documented support and further suggestions on alternatives, please post to either:
- [Visual Studio on StackOverflow](https://stackoverflow.com/questions/tagged/visual-studio)
-or-
- [Visual Studio developer community](https://developercommunity.visualstudio.com/spaces/8/index.html)

...with a provided link back to this issue.

**Comment by Mikejo5000** [comment] 2019-12-18 19:14
It appears that large switch statements are flagged routinely for this and this is by design. @mavasani Is there any recommendation how to reduce complexity in a large switch statement?

**Comment by Mikejo5000** [comment] 2019-12-18 19:17
Looking around, looks like there are some different recommendations for replacing a large switch statement, like using polymorphism:
https://stackoverflow.com/questions/126409/ways-to-eliminate-switch-in-code

**Comment by ChrisTorng** [comment] 2019-12-19 09:07
Other suggestions, like polymorphism,  makes it even more complex. You may suggest us to "Consider using polymorphism to replace the `switch` statement", but not suggest us to "Use polymorphism to reduce `switch` statement's complexity". The reason not to use `switch` statement is not about complexity, but maybe some other design pattern principles. That maybe becomes another rule, but not "CA1502: Avoid excessive complexity".

**Comment by Mikejo5000** [comment] 2019-12-20 18:32
OK, thanks. Sounds like the request is for a change to the rule behavior (ignore a large switch statement) more than a doc bug, since, as you pointed out, large switches are already discussed in the "When to exclude" section. Would you either open the issue here, https://github.com/dotnet/roslyn-analyzers/issues, or use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

**Closed by Mikejo5000** 2019-12-20 18:32 UTC
Labels: Pri2, doc-enhancement, visual-studio-windows/prod, vs-ide-code-analysis/tech
