### ISSUE TITLE
離線安裝仍出現下載失敗的解決辦法

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#1818] opened 2018-11-05 20:18 UTC
@dannypc1628 commented on [Sat Nov 03 2018](https://github.com/MicrosoftDocs/visualstudio-docs.zh-tw/issues/37)

在vs2017layout中尋找錯誤訊息中，需要下載的套件名稱
如果有該套件存在，可能因為套件名稱後面有漏字，導致安裝程式以為無該套件
補上闕漏的字就可以正常安裝
詳細 https://dannyliu.me/fix-visual-studio-2017-offline-install-error/

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [建立 Visual Studio 的離線安裝 - Visual Studio](https://docs.microsoft.com/zh-tw/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-tw/blob/live/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by CeciAc** [comment] 2018-11-05 20:20
Hi team, 
I'm moving this here since I understand the user is making suggestions on the documentation:

Backtranslation: 
_Offline installation still has a download failure solution_  

_The name of the kit to download in the error message in vs2017layout
If the kit exists, it may be because the package name is followed by a missing word, causing the installer to think that there is no such package.
Fill in the missing words and you can install them normally.
Details https://dannyliu.me/fix-visual-studio-2017-offline-install-error/_

**Comment by TerryGLee** [comment] 2018-11-06 00:07
@CeciAc Thanks; this is a duplicate of [#1807](https://github.com/MicrosoftDocs/visualstudio-docs/issues/1807), so we'll close this as such.

**Closed by TerryGLee** 2018-11-06 00:07 UTC
Labels: area - installation, duplicate
