### ISSUE TITLE
"An error occurred while creating the new data source: An error occurred while generating the data source."

### ISSUE THREAD

**Issue by JohnBrea** [MicrosoftDocs/visualstudio-docs#4145] opened 2019-10-17 23:19 UTC
Freshly installed VS2019.
In step 7 of "Add a data source", I get the expected message that says the database doesn't contain any objects so I choose Finish. 
I then get a popup:

"An error occurred while creating the new data source: An error occurred while generating the data source."

In the Error List, there are two errors with Description of:

"Input file content passed to generator is null or empty."
"inputFileContent"

for project SampleDatabaseWalkthrough	
and file C:\Users\Green.000\source\repos\SampleDatabaseWalkthrough\SampleDatabaseWalkthrough\SampleDatabaseDataSet.xsd		

Tried this a few times without success.

**Comment by JohnBrea** [comment] 2019-10-17 23:29
I've obviousy done something wrong as was expecting the following to appear in my original comment.

Document Details
⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.
ID: 11d19e1d-1448-e5b3-6580-9b11042e03ab
Version Independent ID: 549472fa-f3be-53bc-cf9f-170c1183c834
Content: [Create a database file and use table designer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/create-a-sql-database-by-using-a-designer?view=vs-2019#feedback)
Content Source: [docs/data-tools/create-a-sql-database-by-using-a-designer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/create-a-sql-database-by-using-a-designer.md)
Product: visual-studio-windows
Technology: vs-data-tools
GitHub Login: @gewarren
Microsoft Alias: gewarren

**Comment by msebolt** [comment] 2019-10-18 16:33
@JohnBrea  Thank you for the feedback, assigning this to the author for review.

**Comment by gewarren** [comment] 2019-10-18 19:16
@JohnBrea Thanks for letting us know. I was able to reproduce the problem in a .NET Core app but not in a .NET Framework app. I assume you're using .NET Core?

![image](https://user-images.githubusercontent.com/24882762/67121617-d01af600-f1a0-11e9-9266-e272cbbc9d08.png)

To make sure that this product problem is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool. When you do this, your report becomes part of the work items that are tracked on Visual Studio [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). There, you can engage directly with the engineering team while they address and fix the problem.

**Comment by msrama5** [comment] 2020-02-25 00:53
Any update on this, I am using vs2019 community edition and seeing the same error today when connecting to sql database

**Comment by billjacobi** [comment] 2020-05-07 19:33
Same error as above using .NET Core in creating a Windows Form app.

**Comment by ghogen** [comment] 2020-06-03 23:01
These procedures only apply to .NET Framework. I added a note to this effect.

**Comment by ghogen** [comment] 2020-06-03 23:17
The DataSet and these procedures won't be recommended for use in future, due to various issues, so for now the best we can do is mark these as applicable only to .NET Framework.

**Closed** 2020-06-03 23:47 UTC
Labels: Pri2, doc-bug, visual-studio-windows/prod, vs-data-tools/tech

**Comment by imrizwanafzal** [comment] 2020-07-13 15:38
I am having the same issue, please confirm do you have a connection string that doesn't contain password to connection?

**Comment by neerajmehtausa** [comment] 2023-01-29 03:59
I am having same issue when I am trying to create a data source for a SQL server database using VS 2019 C# Community Edition. I have this working in one of my VS 2019 Community edition - VB.Net solution on same computer but not in C#.
