### ISSUE TITLE
LinkedIn Learning 3 months free NOT ACTIVATING!!!

### ISSUE THREAD

**Issue by davenisarg** [MicrosoftDocs/visualstudio-docs#2971] opened 2019-04-01 18:45 UTC
I am trying to activate my LinkedIn Learning three months free trial but link isn’t working and it says ‘We are out of codes, Please try later'

**Comment by TerryGLee** [comment] 2019-04-01 20:02
@evanwindom FYI

**Comment by evanwindom** [comment] 2019-04-01 21:17
@davenisarg Thanks for reaching out.  We're aware of the issue and are working on a resolution.  Please do not make additional attempts to retrieve the code as this may cause further errors.  I will post here once the issue is resolved.

Thank you for your patience.

**Comment by davenisarg** [comment] 2019-04-03 13:46
@evanwindom Sorry I closed it by mistake. May I know whether it is solved or not?

**Comment by davenisarg** [comment] 2019-04-13 15:03
Hello @evanwindom and @TerryGLee,

I am still getting this error,

"Oops! We've temporarily run out. Please try again later."

**Comment by evanwindom** [comment] 2019-06-06 21:58
LinkedIn is no longer offering the 3-month Premium benefit through Visual Studio Dev Essentials.  A one-month free trial is available at https://www.linkedin.com/learning/me.

**Comment by TerryGLee** [comment] 2019-06-10 20:13
@evanwindom Thanks for providing us with the status of the LinkedIn Learning benefit. We are closing this issue now.

**Closed by TerryGLee** 2019-06-10 20:13 UTC
Labels: area - subscriptions, support-request
