### ISSUE TITLE
Tracking Points and Tracking Spans should reference SpanTrackingMode members

### ISSUE THREAD

**Issue by gosali** [MicrosoftDocs/visualstudio-docs#1081] opened 2018-06-05 21:19 UTC
@AdmiralSnyder commented on [Tue Jun 05 2018](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/8)

the following paragraph should reference SpanTrackingMode members:
An ITrackingSpan represents a range of characters instead of just one position. Its behavior is determined by its SpanTrackingMode. If the span tracking mode is SpanTrackingMode, the tracking span grows to incorporate text inserted at its edges; if the span tracking mode is SpanTrackingMode, the tracking span does not incorporate text inserted at its edges. However, if the span tracking mode is SpanTrackingMode, an insertion pushes the current position toward the start, and if the span tracking mode SpanTrackingMode, an insertion pushes the current position toward the end. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 3f9f6314-07f7-4a22-2f4a-e29636bdda91
* Version Independent ID: d109c631-e7c0-5364-c6e4-12e2c47b1974
* Content: [In den Editor](https://docs.microsoft.com/de-de/visualstudio/extensibility/inside-the-editor)
* Content Source: [docs/extensibility/inside-the-editor.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/extensibility/inside-the-editor.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

---

@gosali commented on [Tue Jun 05 2018](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/8#issuecomment-394863928)

Hello, @AdmiralSnyder , 
 
Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - XXX. 
 
We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team

**Comment by gewarren** [comment] 2019-01-10 02:05
This is a dupe of #724 which I'm currently fixing, so closing this issue.

**Closed by gewarren** 2019-01-10 02:05 UTC
Labels: area - extensibility, doc feedback
