### ISSUE TITLE
How to suppress CA2007 Warning!

### ISSUE THREAD

**Issue by TanvirArjel** [MicrosoftDocs/visualstudio-docs#4034] opened 2019-10-02 14:58 UTC
Documentation said:

> You can suppress this warning if you know that the consumer is not a graphical user interface (GUI) app or if the consumer does not have a SynchronizationContext.

 But did not tell how to suppress this.  Would any anybody tell how can I suppress this in ASP.NET Core Application from `.editorconfig`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02d637a6-6f73-c865-94ea-28ca5d9861a0
* Version Independent ID: df24f234-848f-e04c-488d-6b6346e51fa6
* Content: [CA2007: Do not directly await a Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2007-do-not-directly-await-task?view=vs-2017#feedback)
* Content Source: [docs/code-quality/ca2007-do-not-directly-await-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca2007-do-not-directly-await-task.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment] 2019-10-02 19:11
@TanvirArjel  Thank you for the question.

Does [manually configure rule severity](https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#manually-configure-rule-severity) not apply?

Assigning this to the author now.

**Comment by TanvirArjel** [comment] 2019-10-03 03:28
@msebolt Thank you. Your specified link helped me. I have done this as follows:

```
[*.cs]
dotnet_diagnostic.CA2007.severity = none
```

It should have been mentioned in this documentation.

**Comment by gewarren** [comment] 2019-10-03 18:02
@TanvirArjel Thanks, that is a good suggestion.

**Comment by vankampenp** [comment] 2019-11-14 20:21
As asp.net core applications do not have a context, this warning should not be on by default for asp.net core.

**Comment by udlose** [comment] 2019-12-10 23:18
The document needs to be changed.  It says to use:
`dotnet_code_quality.CA2007.exclude_async_void_methods = true` which does not disable the warning.  

The correct syntax is:
`dotnet_diagnostic.CA2007.severity = none`

**Comment by Mikejo5000** [comment] 2019-12-19 23:11
@udlose Looks like exclude_async_void_methods only excludes asynchronous methods that don't return a value, and is not the general way to suppress the warning (for which, as you mentioned, the correct syntax is:
dotnet_diagnostic.CA2007.severity = none).

If exclude_async_void_methods is not working, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

The original issue mentioned by @TanvirArjel applies to most or all of the warnings topics, not just this one. However, there is a link to the .editorconfig topic already at the end of the Configurability section.

**Closed by Mikejo5000** 2019-12-19 23:11 UTC
Labels: Pri2, doc-enhancement, visual-studio-windows/prod, vs-ide-code-analysis/tech

**Comment by d4e666** [comment] 2020-04-20 18:27
if the analyzers were written correctly, they would take the type of assembly they are used in into account and USERS would not have to suffer from YOUR screwups, but hey that why you don't have REAL developers on your staff right, otherwise YOUR staff would be the ones finding all the bugs instead of END USERS WASTING TIME REPORTING YOUR SHIT. How many "features" have you produced that have NO regression and where bugs are not still open after 10 years because YOU don't think they matter????? that'ts right NONE!!!!!! you can't even apply your own coding rules
