### ISSUE TITLE
Source Control definition

### ISSUE THREAD

**Issue by dannyspeagle** [MicrosoftDocs/visualstudio-docs#1148] opened 2018-06-20 22:41 UTC
I came here to learn what 'Source Control' is.  But, there is no definition here.  On the very page that is supposed to discuss 'Source Control', I might add.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d694b45-7f91-63cb-e02e-352af73e54a4
* Version Independent ID: 0162239a-2140-1f7f-2bc1-0e4686637621
* Content: [Source Control - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/source-control)
* Content Source: [docs/extensibility/internals/source-control.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/internals/source-control.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gregvanl** [comment] 2018-06-20 22:51
Closing as duplicate of https://github.com/MicrosoftDocs/visualstudio-docs/issues/1147

**Closed by gregvanl** 2018-06-20 22:51 UTC
