### ISSUE TITLE
Should provide instructions in the FAQ section as to how to request a "Closed" ticket to be considered for re-Opening

### ISSUE THREAD

**Issue by danieljllo** [MicrosoftDocs/visualstudio-docs#4760] opened 2020-02-06 13:54 UTC
I was going to post a new suggestion and found that someone already made it a few months ago, but the suggestion was Closed because it got no votes or additional comments:
https://developercommunity.visualstudio.com/idea/474641/tests-results-tree-in-pipelines-should-include-the.html

I went ahead and added a comment two days ago as to why I think you should consider reopening the suggestion, but I have not heard back from Microsoft, so I'm not sure what is the recommended way for requesting a suggestion to be reopened. Also when I tried to Up vote the suggestion the system told me that I cannot Up vote closed suggestions.

Your FAQ should have a section that clearly details how we can request a closed suggestion to be reopened.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 785f2716-1297-f343-24fa-705a42c2ff64
* Version Independent ID: 732cf4ab-6056-31a6-abda-c63a37f90e45
* Content: [Suggest a feature - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2017#feedback)
* Content Source: [docs/ide/suggest-a-feature.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/suggest-a-feature.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @seaniyer
* Microsoft Alias: **seiyer**

**Comment by WilliamAntonRohm** [comment] 2020-02-07 23:14
@danieljllo -- thank you for your feedback on feedback.  You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback). 

@seaniyer -- please look into this possible documentation update.

near-duplicate of #4759.

**Comment by mariaghiondea** [comment] 2020-04-03 01:52
Please report this suggestion by following this link: https://developercommunity.visualstudio.com/content/idea/post.html?space=8. This will allow us and you to easily track the status of your item, as well as have the community involved in providing comments, votes, answers, which will give us more context and understanding of impact.

**Closed by mariaghiondea** 2020-04-03 01:52 UTC
Labels: Pri2, docs-experience, visual-studio-windows/prod, vs-ide-general/tech
