### ISSUE TITLE
The build command does not produce any output

### ISSUE THREAD

**Issue by MeLight** [MicrosoftDocs/visualstudio-docs#4775] opened 2020-02-10 16:15 UTC
I'm checking the bin and obj folders, nothing there. What am I doing wrong? How do I make it generate .exe file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f41d57f6-25bf-bc84-7ba8-4cb4ecedac05
* Version Independent ID: 69c3bd43-6c2b-834b-18d2-0555a79961a7
* Content: [Walkthrough: Using MSBuild - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/walkthrough-using-msbuild?view=vs-2019#feedback)
* Content Source: [docs/msbuild/walkthrough-using-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/walkthrough-using-msbuild.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment] 2020-02-11 00:16
@MeLight -- Yuri, thank you for your questions.  You may find answers here:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@ghogen -- Gordon, please look into this potential documentation issue.

**Comment by ghogen** [comment] 2020-02-11 00:39
@MeLight Are you getting any error messages or build logs?

**Comment by MeLight** [comment] 2020-02-11 08:07
No errors. Just silently not doing anything when running the Dev Cmd Prompt from Visual Studio. But when opening regular command line, and running this:

 `%comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"`

everything seems to be working fine afterwards.

**Comment by ghogen** [comment] 2020-02-21 21:17
I just went through this on Visual Studio 2019 and was not able to reproduce the problem.  I'll go ahead and close this now, but if you think there's a bug in Visual Studio here, you can submit a bug report to https://developercommunity.visualstudio.com/spaces/8/index.html

**Closed by ghogen** 2020-02-21 21:17 UTC
Labels: Pri1, doc-bug, msbuild/tech, support-request, visual-studio-windows/prod
