### ISSUE TITLE
ManifestResourceName

### ISSUE THREAD

**Issue by SixPines** [MicrosoftDocs/visualstudio-docs#7194] opened 2021-10-26 21:32 UTC
ManifestResourceName does not appear in my VS2017 project file so this document is of no help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54968ac1-07eb-8537-1a9d-13dccc31f259
* Version Independent ID: af818105-b95d-8f5a-8152-a4414962921d
* Content: [MSB3577: Two output file names resolved to the same output path: 'path' - MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/errors/msb3577?f1url=%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(MSBuild.GenerateResource.DuplicateOutputFilenames)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%253Dv4.8)%26rd%3Dtrue&view=vs-2017)
* Content Source: [docs/msbuild/errors/msb3577.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/errors/msb3577.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment] 2021-11-22 22:25
@SixPines. Thanks for the feedback.

The ManifestResourceName is just an example of one way this error could occur. If you solved this, let us know what the root cause. It could be that another example can be added.

**Comment by ghogen** [comment] 2021-11-23 19:53
Closing this issue, but if you have an example, let us know.

**Closed by ghogen** 2021-11-23 19:53 UTC
Labels: visual-studio-windows/prod, msbuild/tech, Pri2, doc-enhancement
