### ISSUE TITLE
Package Caches and Offline Installs

### ISSUE THREAD

**Issue by VikingByNature** [MicrosoftDocs/visualstudio-docs#6399] opened 2021-02-20 15:17 UTC
If I create an offline installation layout using only a few selected workloads and then install these same workloads from that layout with either the `--Cache` or `--NoCache` options along with the `--NoWeb` option, would caching to a different directory still take place **OR** would _neither_ of the cache options, including `--Path Cache="{ProgramPath}"`, even apply to offline layout installs?

In addition, does specifying `--NoWeb` for an install from an offline layout simply disable the package caching altogether as well, thereby causing those other cache options to be ignored if they are specified?

And also, if the cache options still _do_ apply to installs from an offline layout _without_ the use of `--NoWeb`, would specifying `--NoCache` for such an install actually delete the contents of the offline layout (which I do not want to happen) as it would still be considered cached data?

If you could please list the answer in the document that would greatly be appreciated in order to avoid confusion.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30769f4b-cb77-a9e1-8386-eb04fc85fc8f
* Version Independent ID: a09a3a57-fda3-2c68-7f68-4207764fc2c7
* Content: [Disable or move the package cache - Visual Studio](https://docs.microsoft.com/en-ca/visualstudio/install/disable-or-move-the-package-cache?view=vs-2019)
* Content Source: [docs/install/disable-or-move-the-package-cache.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/disable-or-move-the-package-cache.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment] 2021-02-22 21:20
Duplicate of #6400

**Closed by WilliamAntonRohm** 2021-02-22 21:20 UTC
Labels: Pri2, cba, duplicate, visual-studio-windows/prod, vs-installation/tech
