### ISSUE TITLE
Undeclared Identifier 'Textox'

### ISSUE THREAD

**Issue by resun555** [MicrosoftDocs/visualstudio-docs#425] opened 2018-01-05 02:17 UTC
To the Author, you might have note that 'TextBox control with Stretch property'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e155a58-40dd-c4f9-5089-dabc1870c5a8
* Version Independent ID: e257ebf0-4506-408f-c078-18a35820fe60
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/step-5-add-controls-to-your-form#)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/step-5-add-controls-to-your-form.md)

**Comment by gewarren** [comment] 2018-01-05 17:55
Dupe of #426

**Closed by gewarren** 2018-01-05 17:55 UTC
