### ISSUE TITLE
Add documentation for Usage rule CA2245 (AvoidPropertySelfAssignment) in CodeQuality.Analyzers doc-bug

### ISSUE THREAD

**Issue by mclayton7** [MicrosoftDocs/visualstudio-docs#3510] opened 2019-06-21 11:05 UTC
Rule implementation: https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/AvoidPropertySelfAssignment.cs

@gewarren I'm not sure how to make this link back to the visual studio page here: https://docs.microsoft.com/en-us/visualstudio/code-quality/usage-warnings?view=vs-2019

**Comment by gewarren** [comment] 2019-06-21 13:09
Closing as a dupe of #3511.

**Closed by gewarren** 2019-06-21 13:09 UTC
Labels: area - code analysis
