### ISSUE TITLE
Didn't work

### ISSUE THREAD

**Issue by GuyFleegman** [MicrosoftDocs/visualstudio-docs#4089] opened 2019-10-10 15:58 UTC
I followed the above instructions.  However, Visual Studio is still giving me the warning whenever I build my project:
1&gt;Failed to connect to VCTIP: 'CreateFile' failed with 2
1&gt;Not launching VCTIP: it is flagged as unstable
1&gt;Telemetry event upload failed: 'Failed to open connection to VCTIP'
Which seems to indicate that VCTIP is still running, even though I've "opted out".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d08893df-9565-a578-3dda-9fb5c7d3528c
* Version Independent ID: 23d30ca6-71e7-aece-d032-9b0ea5c81f58
* Content: [Customer Experience Improvement Program - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-experience-improvement-program?view=vs-2017#feedback)
* Content Source: [docs/ide/visual-studio-experience-improvement-program.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/visual-studio-experience-improvement-program.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @PoulChapman
* Microsoft Alias: **tglee**

**Comment by msebolt** [comment] 2019-10-10 19:14
@GuyFleegman Thank you for the feedback.

This was labelled as "bug by design" by the product team in [this post](https://developercommunity.visualstudio.com/content/problem/416745/what-is-vctip-and-how-to-disable-it.html) on the **Visual Studio community**.

You will need to either add your comment there or start a new ticket.

**Comment by WilliamAntonRohm** [comment] 2019-10-11 22:15
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Closed by WilliamAntonRohm** 2019-10-11 22:15 UTC
Labels: Pri2, product-feedback, visual-studio-windows/prod, vs-ide-general/tech
