### ISSUE TITLE
Instructions do not produce a working container

### ISSUE THREAD

**Issue by klm1** [MicrosoftDocs/visualstudio-docs#4317] opened 2019-11-13 23:01 UTC
The instructions at [Install Build Tools into a container](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019) do not produce a working container. 

Step 5 (`docker build -t buildtools2019:latest -m 2GB .`) of the directions produces the following warning:

` ---> [Warning] Shell-form ENTRYPOINT and exec-form CMD may have unexpected results`

And then running the container as directed (`docker run -it buildtools2019`) produces:

```
docker: Error response from daemon: container bde8fd3c54cb5ebd9c09d296c5c85b87561a90059761f18ca2bac92e933a576a encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2)
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail: onecore\vm\compute\management\orchestration\vmhostedcontainer\processmanagement.cpp(173)\vmcomputeagent.exe!00007FF604DB9D2B: (caller: 00007FF604D6E13A) Exception(2) tid(394) 80070002 The system cannot find the file specified.
    CallContext:[\Bridge_ProcessMessage\VmHostedContainer_ExecuteProcess]
 Provider: 00000000-0000-0000-0000-000000000000] extra info: {"CommandLine":"\"cmd /S /C C:\\BuildTools\\Common7\\Tools\\VsDevCmd.bat \u0026\u0026\" powershell.exe -NoLogo -ExecutionPolicy Bypass","WorkingDirectory":"C:\\","Environment":{"COMPLUS_NGenProtectedProcess_FeatureEnabled":"0","NUGET_VERSION":"4.4.1","ROSLYN_COMPILER_LOCATION":"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\MSBuild\\Current\\Bin\\Roslyn"},"EmulateConsole":true,"CreateStdInPipe":true,"CreateStdOutPipe":true,"ConsoleSize":[31,177]}.
```

This all done on a Windows 10, version 1903 system running Docker Desktop 2.1.04 (Docker Engine 19.03.4).

**Comment by msebolt** [comment] 2019-11-14 05:03
@klm1  Thank you for the feedback, assigning this to the author for review.

**Comment by heaths** [comment] 2019-11-14 05:38
This is a duplicate of #3713, which is caused by a regression in Docker for Windows. Unfortunately, you'll have to change the `ENTRYPOINT` to fit your use case, which will be custom and not easy to document. The hope was the regression will be fixed.

@msebolt, I'm also no longer on the setup team. Could you change the owner?

**Comment by klm1** [comment] 2019-11-14 13:16
It seems to me the goal of these instructions was to give one example of how the VS built tools can be loaded into and run from Docker. If it's no longer possible to document a working example of that, would it be better to (perhaps temporarily) remove the page?

**Comment by heaths** [comment] 2019-11-14 15:32
@TerryGLee I could make one more edit to at least give people an interactive-only shell that couldn't be used for direct automation. Does that work for you? Honestly, I doubt Docker for Windows will fix the underlying issue given the open bug.

**Comment by TerryGLee** [comment] 2019-11-15 01:01
@heaths An edit would be much appreciated. :)

**Comment by Artem-B** [comment] 2019-11-29 03:38
Perhaps it would be possible to capture the environment set by `VsDevCmd.bat` and automatically generate ENV lines to be added to the Dockerfile? One would need to build the container twice, but at least this way we'd have a container usable for automation.

**Comment by heaths** [comment] 2019-11-30 21:48
I had considered that, but vsdevcmd has different options for the target architecture. How much those affect compiler/linker arguments over command-line arguments (or lack thereof) I don't know.

**Comment by Artem-B** [comment] 2019-12-01 01:12
I've ended up with this script: https://github.com/Artem-B/tf-win/blob/master/setup_build_env.py
First I build an image with MSVC installed, with no environment set up yet. Then I tell this script to run `vsdevcmd` with given arguments in the container, capture environment after that and run 'docker commit -c....' to replicate the new environment in a new image.

**Comment by Artem-B** [comment] 2019-12-02 02:37
Apparently it's impossible to use `docker commit -c ENV...` to set environment variable to a value that ends with a trailing backslash. Docker strips the trailing backslashes and ends up concatenating `ENV` lines from different `-c` options. This looks like a docker bug to me. This makes it impossible to replicate the environment exactly.  If `VCINSTALLDIR` and `VSINSTALLDIR` do not have trailing backslashes, it apparently causes problems for `vsdevcmd.bat` if it's re-run again. The `ENV` statements in a docker file do not have the same problem, so I ended up using the script above with `--print` and appended its output to the `Dockerfile`.

**Comment by Artem-B** [comment] 2019-12-02 06:11
I've got the script working after all. The work around for https://github.com/docker/for-win/issues/5254 is to use a different escape character.

**Comment by heaths** [comment] 2019-12-03 01:20
Thanks, but vsdevcmd supports different run modes. Capturing the environment fixes it to one, unless users run vsdevcmd again *and* vsdevcmd overwrites those environment variables. The original idea - that worked before the regression - was you can just launch the container and get an interactive prompt, or pass args to vsdevcmd to customize the environment and/or even build and exit, setting `ERRORLEVEL` from the container if applicable. This can't work with the regression and will have to either be interactive or make the user specify the entire command including the shell script. I'm working on testing configuration changes as I have time.

**Comment by Artem-B** [comment] 2019-12-05 20:13
I'm not saying that the script is the solution. It's merely a workaround that's good enough to give me a working container. Making one container per configuration I need is a hassle, but it's quite a bit better than having no container at all.

**Comment by ornellaalt** [comment] 2020-03-26 18:47
Hi @klm1, we've updated the Build Tools documentation [here](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019). Please give the new instructions a try. We look forward to your feedback, and I'll be closing out this issue in the meantime.

**Closed by ornellaalt** 2020-03-26 18:47 UTC
Labels: Pri3, doc-bug, visual-studio-windows/prod, vs-ide-install/tech
