### ISSUE TITLE
Send feedback about "This product" should go to https://github.com/dotnet/roslyn-analyzers/issues

### ISSUE THREAD

**Issue by ashmind** [MicrosoftDocs/visualstudio-docs#4654] opened 2020-01-16 06:45 UTC
If I press "Send feedback about" =&gt; "this product" it redirects me to https://developercommunity.visualstudio.com which is too general.

It seems there is a specific repository that contains this rule (https://github.com/dotnet/roslyn-analyzers) -- should the link go to https://github.com/dotnet/roslyn-analyzers/issues?

![image](https://user-images.githubusercontent.com/166396/72500192-d486a600-3898-11ea-8154-2dcd4f5f892d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c370a407-b61d-0de6-6ac4-9b0ab49216b9
* Version Independent ID: a96e421e-65d3-07ba-097e-3feff2b3c677
* Content: [CA2000: Dispose objects before losing scope - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2000?view=vs-2019)
* Content Source: [docs/code-quality/ca2000.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca2000.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment] 2020-01-16 20:04
@ashmind  Thank you for the feedback.

This issue should acutally be redirected to [Microsoft Docs issues](https://github.com/MicrosoftDocs/feedback/issues).  :)

Since the [roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers) are considered a subset of Visual Studio, this is considered by design.

However, please note we are still in the process of linking the repos and should soon be able to transfer the issues via GitHub:

![Capture](https://user-images.githubusercontent.com/6675884/72558593-dd0abc80-3857-11ea-81fb-a3ac2ff74246.PNG)

@Mikejo5000

**Comment by msebolt** [comment] 2020-01-17 16:01
Closing the issue now.  Please comment below if there are further questions.

**Closed by msebolt** 2020-01-17 16:01 UTC
Labels: Pri2, docs-experience, visual-studio-windows/prod, vs-ide-code-analysis/tech
