### ISSUE TITLE
Incorrect Query

### ISSUE THREAD

**Issue by samryanturner** [MicrosoftDocs/visualstudio-docs#8955] opened 2023-02-14 12:15 UTC
WQL query seems to be missing the '2022' element, despite saying the query will collect it.

select distinct SMS_G_System_COMPUTER_SYSTEM.Name, SMS_G_System_ADD_REMOVE_PROGRAMS.DisplayName, SMS_G_System_ADD_REMOVE_PROGRAMS.Version from SMS_R_System inner join SMS_G_System_COMPUTER_SYSTEM on SMS_G_System_COMPUTER_SYSTEM.ResourceID = SMS_R_System.ResourceId inner join SMS_G_System_ADD_REMOVE_PROGRAMS on SMS_G_System_ADD_REMOVE_PROGRAMS.ResourceID = SMS_R_System.ResourceId where SMS_G_System_ADD_REMOVE_PROGRAMS.DisplayName like "Visual Studio %[a-z]% 201[7,9]"

CORRECTED -

select distinct SMS_R_System.ResourceId, SMS_R_System.ResourceType, SMS_R_System.Name, SMS_R_System.SMSUniqueIdentifier, SMS_R_System.ResourceDomainORWorkgroup, SMS_R_System.Client from  SMS_R_System inner join SMS_G_System_ADD_REMOVE_PROGRAMS on SMS_G_System_ADD_REMOVE_PROGRAMS.ResourceID = SMS_R_System.ResourceId where (SMS_G_System_ADD_REMOVE_PROGRAMS.DisplayName like "Visual Studio %[a-z]% 201[7,9]" or SMS_G_System_ADD_REMOVE_PROGRAMS.DisplayName like "Visual Studio %[a-z]% 2022")

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5e49f2a1-7914-39cd-2c57-ae26759b0598
* Version Independent ID: d68f50a3-c74d-e4c1-4bbc-6dd25d448601
* Content: [Tools for detecting and managing Visual Studio instances](https://learn.microsoft.com/en-us/visualstudio/install/tools-for-managing-visual-studio-instances?view=vs-2022)
* Content Source: [docs/install/tools-for-managing-visual-studio-instances.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/tools-for-managing-visual-studio-instances.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment] 2023-02-15 00:44
Closing as duplicate of #8884.

**Closed by WilliamAntonRohm** 2023-02-15 00:44 UTC
Labels: duplicate, doc-bug, visual-studio-windows/prod, vs-installation/tech, cba, Pri2
