### ISSUE TITLE
Following tutorial, always getting 'Some services are not able to be constructed' error

### ISSUE THREAD

**Issue by shammat** [MicrosoftDocs/visualstudio-docs#4135] opened 2019-10-17 03:36 UTC
Specifically, from Step 4: Expose a web API from your ASP.NET Core app (https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-aspnet-core-ef-step-04?view=vs-2019)

**When trying to build & run application after installing Swagger (and adding copy/paste content from tutorial as described in article):**

System.AggregateException
  HResult=0x80131500
  Message=Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Swashbuckle.AspNetCore.Swagger.ISwaggerProvider Lifetime: Transient ImplementationType: Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator': No constructor for type 'Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator' can be instantiated using services from the service container and default values.) (Error while validating the service descriptor 'ServiceType: Swashbuckle.AspNetCore.SwaggerGen.ISchemaRegistryFactory Lifetime: Transient ImplementationType: Swashbuckle.AspNetCore.SwaggerGen.SchemaRegistryFactory': Failed to compare two elements in the array.)
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at WebApplication1.Program.Main(String[] args) in C:\Users\Jenna\source\repos\WebApplication1\WebApplication1\Program.cs:line 18

Inner Exception 1:
InvalidOperationException: Error while validating the service descriptor 'ServiceType: Swashbuckle.AspNetCore.Swagger.ISwaggerProvider Lifetime: Transient ImplementationType: Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator': No constructor for type 'Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator' can be instantiated using services from the service container and default values.

Inner Exception 2:
InvalidOperationException: No constructor for type 'Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator' can be instantiated using services from the service container and default values.

**Program.cs, including line 18 which is referenced above:**

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.DependencyInjection;
using WebApplication1.Models;

namespace WebApplication1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var host = CreateHostBuilder(args).Build();

            using (var scope = host.Services.CreateScope())
            {
                var services = scope.ServiceProvider;

                try
                {
                    var context = services.GetRequiredService<AppDbContext>();
                    context.Database.EnsureCreated();
                }
                catch (Exception ex)
                {
                    var logger = services.GetRequiredService<ILogger<Program>>();
                    logger.LogError(ex, "An error occurred creating the DB.");
                }
            }

            host.Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
}

_I'm new to this, so it's possible the error is glaringly obvious to someone who knows what they are doing - but I've been able to reproduce the error each time I've started this tutorial from scratch, and have been unable to proceed further than this step in the tutorial, so as a tutorial the doc is failing its purpose._

**Comment by TerryGLee** [comment] 2019-10-21 22:48
@shammat Thanks for letting us know; we'll take a look at it and report back.

**Comment by Rick-Anderson** [comment] 2020-03-31 22:14
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

**Comment by ornellaalt** [comment] 2020-03-31 22:26
Hi @shammat, it seems to be an issue caused by mixing 3.1 and 2.2 which is not supported. Closing out this issue for now, but if you continue to have trouble, please create an issue from the doc page per @Rick-Anderson's instructions.

**Comment by Rick-Anderson** [comment] 2020-03-31 22:26
See  https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.1  for a 3.1 version

**Closed by ornellaalt** 2020-03-31 22:26 UTC
Labels: Pri3, doc-bug, visual-studio-windows/prod, vs-ide-general/tech
