### ISSUE TITLE
Duplicate `Unaffiliated components` Visual Studio components

### ISSUE THREAD

**Issue by icnocop** [MicrosoftDocs/visualstudio-docs#9089] opened 2023-03-26 16:45 UTC
It seems every one of these `Unaffiliated components` component ids are duplicated, with no difference with the name and version:
```
<html><body>
<!--StartFragment-->

Microsoft.VisualStudio.Component.VC.14.33.17.3.ARM | MSVC v143 - VS 2022 C++ ARM build tools (v14.33-17.3) | 17.5.33413.361
-- | -- | --
Microsoft.VisualStudio.Component.VC.14.33.17.3.ARM | MSVC v143 - VS 2022 C++ ARM build tools (v14.33-17.3) | 17.5.33413.361
Microsoft.VisualStudio.Component.VC.14.33.17.3.ARM.Spectre | MSVC v143 - VS 2022 C++ ARM Spectre-mitigated libs (v14.33-17.3) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.ARM.Spectre | MSVC v143 - VS 2022 C++ ARM Spectre-mitigated libs (v14.33-17.3) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.ARM64 | MSVC v143 - VS 2022 C++ ARM64 build tools (v14.33-17.3) | 17.5.33413.361
Microsoft.VisualStudio.Component.VC.14.33.17.3.ARM64 | MSVC v143 - VS 2022 C++ ARM64 build tools (v14.33-17.3) | 17.5.33413.361
Microsoft.VisualStudio.Component.VC.14.33.17.3.ARM64.Spectre | MSVC v143 - VS 2022 C++ ARM64 Spectre-mitigated libs (v14.33-17.3) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.ARM64.Spectre | MSVC v143 - VS 2022 C++ ARM64 Spectre-mitigated libs (v14.33-17.3) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.ATL | C++ v14.33 (17.3) ATL for v143 build tools (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.ATL | C++ v14.33 (17.3) ATL for v143 build tools (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.ATL.ARM | C++ v14.33 (17.3) ATL for v143 build tools (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.ATL.ARM | C++ v14.33 (17.3) ATL for v143 build tools (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.ATL.ARM.Spectre | C++ v14.33 (17.3) ATL for v143 build tools with Spectre Mitigations (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.ATL.ARM.Spectre | C++ v14.33 (17.3) ATL for v143 build tools with Spectre Mitigations (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.ATL.ARM64 | C++ v14.33 (17.3) ATL for v143 build tools (ARM64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.ATL.ARM64 | C++ v14.33 (17.3) ATL for v143 build tools (ARM64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.ATL.ARM64.Spectre | C++ v14.33 (17.3) ATL for v143 build tools with Spectre Mitigations (ARM64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.ATL.ARM64.Spectre | C++ v14.33 (17.3) ATL for v143 build tools with Spectre Mitigations (ARM64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.ATL.Spectre | C++ v14.33 (17.3) ATL for v143 build tools with Spectre Mitigations (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.ATL.Spectre | C++ v14.33 (17.3) ATL for v143 build tools with Spectre Mitigations (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.CLI.Support | C++/CLI support for v143 build tools (14.33-17.3) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.CLI.Support | C++/CLI support for v143 build tools (14.33-17.3) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.MFC | C++ v14.33 (17.3) MFC for v143 build tools (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.MFC | C++ v14.33 (17.3) MFC for v143 build tools (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.MFC.ARM | C++ v14.33 (17.3) MFC for v143 build tools (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.MFC.ARM | C++ v14.33 (17.3) MFC for v143 build tools (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.MFC.ARM.Spectre | C++ v14.33 (17.3) MFC for v143 build tools with Spectre Mitigations (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.MFC.ARM.Spectre | C++ v14.33 (17.3) MFC for v143 build tools with Spectre Mitigations (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.MFC.ARM64 | C++ v14.33 (17.3) MFC for v143 build tools (ARM64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.MFC.ARM64 | C++ v14.33 (17.3) MFC for v143 build tools (ARM64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.MFC.ARM64.Spectre | C++ v14.33 (17.3) MFC for v143 build tools with Spectre Mitigations (ARM64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.MFC.ARM64.Spectre | C++ v14.33 (17.3) MFC for v143 build tools with Spectre Mitigations (ARM64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.MFC.Spectre | C++ v14.33 (17.3) MFC for v143 build tools with Spectre Mitigations (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.MFC.Spectre | C++ v14.33 (17.3) MFC for v143 build tools with Spectre Mitigations (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.x86.x64 | MSVC v143 - VS 2022 C++ x64/x86 build tools (v14.33-17.3) | 17.5.33413.361
Microsoft.VisualStudio.Component.VC.14.33.17.3.x86.x64 | MSVC v143 - VS 2022 C++ x64/x86 build tools (v14.33-17.3) | 17.5.33413.361
Microsoft.VisualStudio.Component.VC.14.33.17.3.x86.x64.Spectre | MSVC v143 - VS 2022 C++ x64/x86 Spectre-mitigated libs (v14.33-17.3) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.33.17.3.x86.x64.Spectre | MSVC v143 - VS 2022 C++ x64/x86 Spectre-mitigated libs (v14.33-17.3) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.ARM | MSVC v143 - VS 2022 C++ ARM build tools (v14.34-17.4) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.ARM | MSVC v143 - VS 2022 C++ ARM build tools (v14.34-17.4) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.ARM.Spectre | MSVC v143 - VS 2022 C++ ARM Spectre-mitigated libs (v14.34-17.4) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.ARM.Spectre | MSVC v143 - VS 2022 C++ ARM Spectre-mitigated libs (v14.34-17.4) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.ARM64 | MSVC v143 - VS 2022 C++ ARM64/ARM64EC build tools (v14.34-17.4) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.ARM64 | MSVC v143 - VS 2022 C++ ARM64/ARM64EC build tools (v14.34-17.4) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.ARM64.Spectre | MSVC v143 - VS 2022 C++ ARM64/ARM64EC Spectre-mitigated libs (v14.34-17.4) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.ARM64.Spectre | MSVC v143 - VS 2022 C++ ARM64/ARM64EC Spectre-mitigated libs (v14.34-17.4) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.ATL | C++ v14.34 (17.4) ATL for v143 build tools (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.ATL | C++ v14.34 (17.4) ATL for v143 build tools (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.ATL.ARM | C++ v14.34 (17.4) ATL for v143 build tools (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.ATL.ARM | C++ v14.34 (17.4) ATL for v143 build tools (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.ATL.ARM.Spectre | C++ v14.34 (17.4) ATL for v143 build tools with Spectre Mitigations (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.ATL.ARM.Spectre | C++ v14.34 (17.4) ATL for v143 build tools with Spectre Mitigations (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.ATL.ARM64 | C++ v14.34 (17.4) ATL for v143 build tools (ARM64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.ATL.ARM64 | C++ v14.34 (17.4) ATL for v143 build tools (ARM64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.ATL.ARM64.Spectre | C++ v14.34 (17.4) ATL for v143 build tools with Spectre Mitigations (ARM64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.ATL.ARM64.Spectre | C++ v14.34 (17.4) ATL for v143 build tools with Spectre Mitigations (ARM64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.ATL.Spectre | C++ v14.34 (17.4) ATL for v143 build tools with Spectre Mitigations (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.ATL.Spectre | C++ v14.34 (17.4) ATL for v143 build tools with Spectre Mitigations (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.CLI.Support | C++/CLI support for v143 build tools (14.34-17.4) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.CLI.Support | C++/CLI support for v143 build tools (14.34-17.4) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.MFC | C++ v14.34 (17.4) MFC for v143 build tools (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.MFC | C++ v14.34 (17.4) MFC for v143 build tools (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.MFC.ARM | C++ v14.34 (17.4) MFC for v143 build tools (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.MFC.ARM | C++ v14.34 (17.4) MFC for v143 build tools (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.MFC.ARM.Spectre | C++ v14.34 (17.4) MFC for v143 build tools with Spectre Mitigations (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.MFC.ARM.Spectre | C++ v14.34 (17.4) MFC for v143 build tools with Spectre Mitigations (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.MFC.ARM64 | C++ v14.34 (17.4) MFC for v143 build tools (ARM64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.MFC.ARM64 | C++ v14.34 (17.4) MFC for v143 build tools (ARM64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.MFC.ARM64.Spectre | C++ v14.34 (17.4) MFC for v143 build tools with Spectre Mitigations (ARM64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.MFC.ARM64.Spectre | C++ v14.34 (17.4) MFC for v143 build tools with Spectre Mitigations (ARM64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.MFC.Spectre | C++ v14.34 (17.4) MFC for v143 build tools with Spectre Mitigations (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.MFC.Spectre | C++ v14.34 (17.4) MFC for v143 build tools with Spectre Mitigations (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.x86.x64 | MSVC v143 - VS 2022 C++ x64/x86 build tools (v14.34-17.4) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.x86.x64 | MSVC v143 - VS 2022 C++ x64/x86 build tools (v14.34-17.4) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.x86.x64.Spectre | MSVC v143 - VS 2022 C++ x64/x86 Spectre-mitigated libs (v14.34-17.4) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.34.17.4.x86.x64.Spectre | MSVC v143 - VS 2022 C++ x64/x86 Spectre-mitigated libs (v14.34-17.4) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.ARM | MSVC v143 - VS 2022 C++ ARM build tools (v14.35-17.5) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.ARM | MSVC v143 - VS 2022 C++ ARM build tools (v14.35-17.5) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.ARM.Spectre | MSVC v143 - VS 2022 C++ ARM Spectre-mitigated libs (v14.35-17.5) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.ARM.Spectre | MSVC v143 - VS 2022 C++ ARM Spectre-mitigated libs (v14.35-17.5) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.ARM64 | MSVC v143 - VS 2022 C++ ARM64/ARM64EC build tools (v14.35-17.5) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.ARM64 | MSVC v143 - VS 2022 C++ ARM64/ARM64EC build tools (v14.35-17.5) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.ARM64.Spectre | MSVC v143 - VS 2022 C++ ARM64/ARM64EC Spectre-mitigated libs (v14.35-17.5) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.ARM64.Spectre | MSVC v143 - VS 2022 C++ ARM64/ARM64EC Spectre-mitigated libs (v14.35-17.5) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.ATL | C++ v14.35 (17.5) ATL for v143 build tools (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.ATL | C++ v14.35 (17.5) ATL for v143 build tools (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.ATL.ARM | C++ v14.35 (17.5) ATL for v143 build tools (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.ATL.ARM | C++ v14.35 (17.5) ATL for v143 build tools (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.ATL.ARM.Spectre | C++ v14.35 (17.5) ATL for v143 build tools with Spectre Mitigations (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.ATL.ARM.Spectre | C++ v14.35 (17.5) ATL for v143 build tools with Spectre Mitigations (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.ATL.ARM64 | C++ v14.35 (17.5) ATL for v143 build tools (ARM64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.ATL.ARM64 | C++ v14.35 (17.5) ATL for v143 build tools (ARM64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.ATL.ARM64.Spectre | C++ v14.35 (17.5) ATL for v143 build tools with Spectre Mitigations (ARM64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.ATL.ARM64.Spectre | C++ v14.35 (17.5) ATL for v143 build tools with Spectre Mitigations (ARM64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.ATL.Spectre | C++ v14.35 (17.5) ATL for v143 build tools with Spectre Mitigations (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.ATL.Spectre | C++ v14.35 (17.5) ATL for v143 build tools with Spectre Mitigations (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.CLI.Support | C++/CLI support for v143 build tools (14.35-17.5) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.CLI.Support | C++/CLI support for v143 build tools (14.35-17.5) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.MFC | C++ v14.35 (17.5) MFC for v143 build tools (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.MFC | C++ v14.35 (17.5) MFC for v143 build tools (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.MFC.ARM | C++ v14.35 (17.5) MFC for v143 build tools (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.MFC.ARM | C++ v14.35 (17.5) MFC for v143 build tools (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.MFC.ARM.Spectre | C++ v14.35 (17.5) MFC for v143 build tools with Spectre Mitigations (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.MFC.ARM.Spectre | C++ v14.35 (17.5) MFC for v143 build tools with Spectre Mitigations (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.MFC.ARM64 | C++ v14.35 (17.5) MFC for v143 build tools (ARM64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.MFC.ARM64 | C++ v14.35 (17.5) MFC for v143 build tools (ARM64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.MFC.ARM64.Spectre | C++ v14.35 (17.5) MFC for v143 build tools with Spectre Mitigations (ARM64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.MFC.ARM64.Spectre | C++ v14.35 (17.5) MFC for v143 build tools with Spectre Mitigations (ARM64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.MFC.Spectre | C++ v14.35 (17.5) MFC for v143 build tools with Spectre Mitigations (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.MFC.Spectre | C++ v14.35 (17.5) MFC for v143 build tools with Spectre Mitigations (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.x86.x64 | MSVC v143 - VS 2022 C++ x64/x86 build tools (v14.35-17.5) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.x86.x64 | MSVC v143 - VS 2022 C++ x64/x86 build tools (v14.35-17.5) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.x86.x64.Spectre | MSVC v143 - VS 2022 C++ x64/x86 Spectre-mitigated libs (v14.35-17.5) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.14.35.17.5.x86.x64.Spectre | MSVC v143 - VS 2022 C++ x64/x86 Spectre-mitigated libs (v14.35-17.5) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.ATL.ARM | C++ ATL for latest v143 build tools (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.ATL.ARM | C++ ATL for latest v143 build tools (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.ATL.ARM.Spectre | C++ ATL for latest v143 build tools with Spectre Mitigations (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.ATL.ARM.Spectre | C++ ATL for latest v143 build tools with Spectre Mitigations (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.ATL.ARM64.Spectre | C++ ATL for latest v143 build tools with Spectre Mitigations (ARM64/ARM64EC) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.ATL.ARM64.Spectre | C++ ATL for latest v143 build tools with Spectre Mitigations (ARM64/ARM64EC) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.ATL.Spectre | C++ ATL for latest v143 build tools with Spectre Mitigations (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.ATL.Spectre | C++ ATL for latest v143 build tools with Spectre Mitigations (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.ATLMFC.Spectre | C++ MFC for latest v143 build tools with Spectre Mitigations (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.ATLMFC.Spectre | C++ MFC for latest v143 build tools with Spectre Mitigations (x86 & x64) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.MFC.ARM | C++ MFC for latest v143 build tools (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.MFC.ARM | C++ MFC for latest v143 build tools (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.MFC.ARM.Spectre | C++ MFC for latest v143 build tools with Spectre Mitigations (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.MFC.ARM.Spectre | C++ MFC for latest v143 build tools with Spectre Mitigations (ARM) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.MFC.ARM64.Spectre | C++ MFC for latest v143 build tools with Spectre Mitigations (ARM64/ARM64EC) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.MFC.ARM64.Spectre | C++ MFC for latest v143 build tools with Spectre Mitigations (ARM64/ARM64EC) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.Redist.MSM | C++ 2022 Redistributable MSMs | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.Redist.MSM | C++ 2022 Redistributable MSMs | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.Runtimes.ARM.Spectre | MSVC v143 - VS 2022 C++ ARM Spectre-mitigated libs (Latest) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.Runtimes.ARM.Spectre | MSVC v143 - VS 2022 C++ ARM Spectre-mitigated libs (Latest) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.Runtimes.ARM64.Spectre | MSVC v143 - VS 2022 C++ ARM64/ARM64EC Spectre-mitigated libs (Latest) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.Runtimes.ARM64.Spectre | MSVC v143 - VS 2022 C++ ARM64/ARM64EC Spectre-mitigated libs (Latest) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.Runtimes.x86.x64.Spectre | MSVC v143 - VS 2022 C++ x64/x86 Spectre-mitigated libs (Latest) | 17.5.33306.270
Microsoft.VisualStudio.Component.VC.Runtimes.x86.x64.Spectre | MSVC v143 - VS 2022 C++ x64/x86 Spectre-mitigated libs (Latest) | 17.5.33306.270

<!--EndFragment-->
</body>
</html>
```

They seem to be duplicated in all "Visual Studio Enterprise", "Visual Studio Professional", and "Visual Studio Community" articles.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b29a1009-5ef4-707b-258e-fe8bbe7275b6
* Version Independent ID: 00fac5a7-fc6d-c9cb-2d26-d820c7055890
* Content: [Visual Studio Enterprise workload and component IDs](https://learn.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2022)
* Content Source: [docs/install/workload-component-id-vs-enterprise.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/workload-component-id-vs-enterprise.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment] 2023-03-27 21:11
This is a duplicate of https://github.com/MicrosoftDocs/visualstudio-docs/issues/9028

**Comment by anandmeg** [comment] 2023-03-27 21:13
@icnocop, thanks for your feedback.

Closing this now as this issue is being tracked by https://github.com/MicrosoftDocs/visualstudio-docs/issues/9028. 

Thanks again!

**Closed by anandmeg** 2023-03-27 21:13 UTC
Labels: doc-bug, visual-studio-windows/prod, vs-installation/tech, Pri2
