### ISSUE TITLE
Problem on  making the DLL available to Python

### ISSUE THREAD

**Issue by ShengrenNiu** [MicrosoftDocs/visualstudio-docs#864] opened 2018-04-27 10:13 UTC
I‘m using the VS 2015. I've already made the DLL available to Python by the first method. But when I run the python file, an exception will be through out. "No module named 'superfastcode' ". There are  .pyd files in the solution folder under Debug and Release and the path of References is correct. However if I copy the .pyd files in the  Release to the subfolder of python solution, the python program can run.

**Comment by ShengrenNiu** [comment] 2018-04-28 00:51
@kraigb Thanks a lot. In order to make you reappear the same problem, I'd like to provide you the environment information. VS: VS2015 Community, Python 3.6 x64 built by Anaconda,  the Property Pages dialog setted Configuration to All Configurations and Platform to x64. In addition, there are .pyd and .lib file in the solution folder under Debug, but no DLL file. I just copy the .pyd and .lib file to the python project folder, and then the Python project can run and debug. And the dialog to add reference for python project is a little different from the C++ project, the latter is the same as the picture. [https://docs.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio](url)

**Comment by ShengrenNiu** [comment] 2018-05-08 14:09
@kraigb Did you also meet this problem?

**Comment by kraigb** [comment] 2018-05-08 22:34
@ShengrenNiu I've been able to reproduce the issue, so will start to investigate why the project to project reference doesn't work. It might take a bit, because most of the Python engineering team, who I need to consult with, are at PyCon as well. Stay tuned.

**Comment by kraigb** [comment] 2018-05-09 12:54
That's likely. The bit that seems to make it work in VS 2017 is that it sets a search path to ..\Debug or ..\Release, which is where the .pyd files get copied. Setting the same search path in VS 2015 manually doesn't work, which suggests that there's a deficiency or bug in the Python tools for that particular version.

As you have a workaround for now, I'm closing this issue. If I learn more I'll report back.

**Closed by kraigb** 2018-05-09 12:54 UTC
Labels: Area - Python and R, support request
