### ISSUE TITLE
Description column in table is truncated without word-wrap or scroll bar

### ISSUE THREAD

**Issue by optikos** [MicrosoftDocs/visualstudio-docs#589] opened 2018-02-20 14:39 UTC
In Safari on Mac, the Description column is truncated without word-wrap or scroll bar.  This does not occur in the Visual Studio 2015 equivalent of this WWWpage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af885617-7979-5fb2-3fc2-d028695e4b8a
* Version Independent ID: a4615f96-f625-4b78-8068-7ae9b343d911
* [Content](https://docs.microsoft.com/en-us/visualstudio/msbuild/resolveassemblyreference-task)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/msbuild/resolveassemblyreference-task.md)
* Service: unspecified

**Comment by Mikejo5000** [comment] 2018-02-28 00:19
@gewarren This is a rendering issue that is not specific to this content. It is also apparent on Chrome, so I suspect this issue is by design.

**Comment by gewarren** [comment] 2018-02-28 00:22
@Mikejo5000 agreed, however it's still not a good customer experience. Can we convert to a bulleted list instead of a table, perhaps?

**Comment by Mikejo5000** [comment] 2018-02-28 01:33
No, its a standard reference template. I can open a bug on it.

**Comment by FlorianKugler42** [comment] 2018-03-02 08:11
This also happens with Firefox 58 on Windows 7. Enlarging the window to span across two monitors doesn't help either, because the content seems to be constrained to roughly 1400px width. If the cause for this is an underlying issue with the template, and other topics are affected as well, this (obviously?) doesn't make it better or less urgent, but on the contrary.

**Comment by Mikejo5000** [comment] 2018-03-04 17:50
Logged as issue 1199561

**Comment by Mikejo5000** [comment] 2018-03-14 20:23
The site people are implementing a fix

**Comment by optikos** [comment] 2018-05-08 22:58
@gewarren, it looks like a scroll bar has NOT, I REPEAT, NOT been added to the bottom of the table of [this WWWpage](https://docs.microsoft.com/en-us/visualstudio/msbuild/resolveassemblyreference-task.)  This issue should not have been closed.  Please re-open it.

**Comment by gewarren** [comment] 2018-05-08 23:17
Issue is resolved on Windows 10 on Edge, Chrome, and Firefox, with the addition of a horizontal scroll bar.

**Comment by FlorianKugler42** [comment] 2018-05-09 06:26
Issue still persists with Firefox 59.0.3 on Windows 7. Please change the title accordingly. And in the future, before closing an issue, please spend at least a minimal amount of verifying on the reported systems. This is not a guessing game... Thank you very much!

**Comment by gewarren** [comment] 2019-01-09 21:38
The scroll bars on wide tables have now been replaced with word wrap. Verified [this table](https://docs.microsoft.com/en-us/visualstudio/msbuild/resolveassemblyreference-task?view=vs-2017) looks good on Chrome, Firefox, and Edge on Windows. If you are still seeing a problem on Safari on Mac, please let us know (I don't have a Mac to verify).

**Closed by gewarren** 2019-01-09 21:38 UTC
Labels: docs experience
