### ISSUE TITLE
Steps don't work when applied to my own app

### ISSUE THREAD

**Issue by colinkiama** [MicrosoftDocs/visualstudio-docs#3791] opened 2019-08-17 20:15 UTC
With an existing app, when I create a unit test project and add a reference to the main app, I end up with payload errors. The tests never run. 

The workaround was to put all code for that will be tested into a library (e.g Universal Windows Class Library) and add a reference to the library in the unit test project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68035759-b6ab-0432-c235-533b44a38eea
* Version Independent ID: e28af1db-9a94-0e2e-f041-ce40eb4a5125
* Content: [Unit testing Visual C# code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/unit-testing-visual-csharp-code-in-a-store-app?view=vs-2019#feedback)
* Content Source: [docs/test/unit-testing-visual-csharp-code-in-a-store-app.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/unit-testing-visual-csharp-code-in-a-store-app.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment] 2019-09-05 22:14
I tried this too and am seeing the same build errors when running the tests:

1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(1822,5): error APPX1101: Payload contains two or more files with the same destination path 'Properties\Default.rd.xml'. Source files: 
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(1822,5): error APPX1101: C:\Users\gw\source\repos\UWP1\UnitTestProject1\Properties\Default.rd.xml
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(1822,5): error APPX1101: C:\Users\gw\source\repos\UWP1\UWP1\Properties\Default.rd.xml

Can you please log an issue by using Report a Problem from Visual Studio? This seems like a bug to me. I did see this recent issue but it's a little different: https://developercommunity.visualstudio.com/content/problem/719729/uwp-apps-importing-microsoftappcentercrashes-do-no.html

**Comment by colinkiama** [comment] 2019-09-07 11:12
I've done it here: https://developercommunity.visualstudio.com/content/problem/726688/uwp-unit-test-doesnt-build-after-adding-reference.html

**Comment by gewarren** [comment] 2019-09-09 16:13
Thank you Colin. I'm closing this documentation issue now. On the off chance this comes back as a problem with the tutorial itself, please comment here and I'll reopen.

**Comment by scout208** [comment] 2019-09-10 19:35
Sorry for raising this again. But @colinkiama did you ever get a response to your feedback? I'm trying to follow the tutorial today and having the same issue.

**Comment by scout208** [comment] 2019-09-10 19:44
My solution was to remove `Default.rd.xml` file from the unit test project as similar to [this](https://github.com/MicrosoftDocs/windows-iotcore-docs/issues/1122) issue.

**Comment by gewarren** [comment] 2019-09-10 19:50
@svetbonev Should the tutorial steps be updated to remove Default.rd.xml from the test project that references the UWP app? Or is there a better way to set up the projects in the tutorial? Thanks.

**Comment by gewarren** [comment] 2019-09-27 19:12
Dupe of #3906.

**Closed** 2019-09-30 17:13 UTC
Labels: Pri2, product-feedback, visual-studio-windows/prod, vs-ide-test/tech
