### ISSUE TITLE
Option dialog help doesn't include Text Editor|Advanced

### ISSUE THREAD

**Issue by richard-broadhurst** [MicrosoftDocs/visualstudio-docs#7745] opened 2022-03-05 08:51 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c03f0366-9eb0-a623-57dc-23c34ca5c73a
* Version Independent ID: 4682db7d-610f-2cf1-523b-34fdc10a016f
* Content: [Options, Text Editor, General - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-general?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(VS.ToolsOptionsPages.Text_Editor.Advanced)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/ide/reference/options-text-editor-general.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/options-text-editor-general.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment] 2022-03-07 18:00
@richard-broadhurst Thanks for letting us know. We plan to have this page published soon; meanwhile, we'll close this issue now as it's a duplicate of an identical & previously reported issue, https://github.com/MicrosoftDocs/visualstudio-docs/issues/7494. 

We appreciate your interest in improving the documentation!

**Closed by TerryGLee** 2022-03-07 18:00 UTC
Labels: duplicate, visual-studio-windows/prod, vs-ide-general/tech, Pri2

**Comment by TerryGLee** [comment] 2022-03-30 18:09
@richard-broadhurst To follow up, this previously missing page is now published; see [Options dialog box: Text Editor > Advanced](https://docs.microsoft.com/visualstudio/ide/reference/options-text-editor-advanced).
