### ISSUE TITLE
How can I update a variety of installations in an enterprise without accidentally installing additional options?

### ISSUE THREAD

**Issue by ducttapecoder-vt** [MicrosoftDocs/visualstudio-docs#4636] opened 2020-01-13 22:48 UTC
Hello,
We have a number of developers in our environment with a wide variety of Visual Studio install options working in an offline environment. Due to the lack of WSUS capability for VS2019, it has become very difficult to update Visual Studio in our environment. For example, it seems necessary to create a layout or a command structure for every single devloper layout to prevent installing additional or missing features when updating these installations. If I create a generic layout with all options, and then try to run it against the various system, it will invariably install the entirety of options to the workstations rather than simply updating the currently installed options. It would be ideal to use a generic layout but have the ability to easily update installations without modifying the installed options. A parameter such as -updateonly which instructs the layout to only update existing options would be useful. It would honestly be much better if there was an easier way to update visual studio offline. Currently, I have to go machine by machine to run the layout. This is very slow and tedious.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an offline installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2019)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by WilliamAntonRohm** [comment] 2020-01-14 00:26
@ducttapecoder-vt, it looks like you’re having an issue with installation. If your Visual Studio installation fails, see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.​ 

We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​ 

Here are a few more support options:​ 

- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 
- Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio). 

And you may find answers here:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by Anton-V-K** [comment] 2020-01-22 06:56
Well, it's strange the issue is closed without addressing the problem.
Specifically I find the recommended step to use **same** command to install VS2019 from cache not very handy.
I'm referring to the following text in [Create an offline installation of Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2019):

> To make sure that you install only the files that you've previously downloaded, use the same command-line options that you used to create the layout cache.

I guess, this is the source of inconvenience for the issue reporter.

Note that it was possible to use a shorter command like `vs_community.exe --locale en-US` to update the existing installation of VS2017 (tested with 15.9.15).
I would expect the same approach works for VS2019 as well.

**Comment by WilliamAntonRohm** [comment] 2020-01-22 19:28
@ornellaalt -- Ornella, please look into this potential documentation issue.

**Comment by ornellaalt** [comment] 2020-06-24 22:47
Hi @ducttapecoder-vt and @Anton-V-K, I believe you are looking for information on how to update a network installation of Visual Studio. See [here](https://docs.microsoft.com/en-us/visualstudio/install/update-a-network-installation-of-visual-studio?view=vs-2019#deploy-an-update-to-client-machines) for how to deploy an update to client machines.

**Closed by ornellaalt** 2020-06-24 22:47 UTC
Labels: Pri1, doc-bug, visual-studio-windows/prod, vs-installation/tech
